### ISSUE TITLE
rf-map used fastq.gz

### ISSUE THREAD

**Issue by omarwagih** [dincarnato/RNAFramework#1]
Is there anyway to use gzipped fastq files with rf-map? Currently I have to unzip them then rezip which is a little annoying.

**Comment by dincarnato** [comment]
Dear Omar,
thank you for your request.
Originally I avoided implementing this as Bowtie1/2 don't have native support for gzipped files.
I have now added support for gzipped files through the use of fifos.
Just do a "git pull" and let me know if everything's working for you (as I only made a couple of tests).
If everything seems fine, I'll close the issue.

Best,
Danny
