### ISSUE TITLE
rf-combine variable typo

### ISSUE THREAD

**Issue by charmichaeld** [dincarnato/RNAFramework#11]
'Global symbol "@commonidx" requires explicit package name (did you forget to declare "my @commonidx"?) at rf-combine line 351.'
Looks like it should be @commonidx1 on lines 351 and 355

**Comment by dincarnato** [comment]
Hi Michael,

thanks for reporting this. I have inadvertently uploaded the devel version I was working on, rather than the working release.
Sorry for this! Fixed now :-)

Best,
Danny
