### ISSUE TITLE
rf-fold: Bareword not allowed error, draco:  could not find modules

### ISSUE THREAD

**Issue by sjhuang6** [dincarnato/RNAFramework#14]
Hi Danny, 

I ran into two more problems while trying to get RNAframework and Draco working: 
1. rf-fold -h give me this error message: 
Bareword "e" not allowed while "strict subs" in use at /RNAFramework/rf-fold line 1258.
Bareword "e" not allowed while "strict subs" in use at /RNAFramework/rf-fold line 1258.
Execution of /RNAFramework/rf-fold aborted due to compilation errors.

The perl I'm using is v5.26.1. Not sure if it is related to that. Every other functions seems to work fine except rf-fold. 

2. For the Draco installation, I got this error after running the cmake command: 
Could NOT find TBB (missing: TBB_INCLUDE_DIRS)
-- Checking for module 'dlib-1'
--   No package 'dlib-1' found
CMake Error at /.conda/envs/draco/share/cmake-3.21/Modules/FindPkg    Config.cmake:554 (message):
  A required package was not found
Call Stack (most recent call first):
  /.conda/envs/draco/share/cmake-3.21/Modules/FindPkgConfig.cmake:    776 (_pkg_check_modules_internal)
  CMakeLists.txt:32 (pkg_check_modules)

Here is the version of prerequisites i got: 
gcc_impl_linux-64         9.3.0
cmake                     3.21.1
openblas                  0.3.3 
armadillo                 9.900.5
boost                     1.76.0 
dlib                      19.22.0
tbb                       2021.3.0 

Let me know if you need more info for these questions. Thanks.

Jimmy

**Comment by dincarnato** [comment]
Dear Jimmy,

for the first issue, just issue a git pull, it should be gone.
For the second, it seems like you are missing the TBB headers. I am not sure on what system you are, but you want to install libtbb-dev (on Ubuntu/Debian) or tbb-devel (Fedora/RedHat/Centos).

Danny

**Comment by sjhuang6** [comment]
Hi Danny,

Yes the first problem is resolved by git pull. The second problem, I'm using centos so I try installing the tbb-devel and I got these two tbb versions now: 
tbb                       2021.3.0             h4bd325d_0    conda-forge
tbb-devel                 2021.3.0             h4bd325d_0    conda-forge

Now I got this error message: 

CMake Error at cmake/Modules/FindTBB.cmake:187 (file):
  file failed to open for reading (No such file or directory):

    /.conda/envs/draco/include/tbb/tbb_stddef.h
Call Stack (most recent call first):
  CMakeLists.txt:10 (find_package)


-- Checking for module 'dlib-1'
--   No package 'dlib-1' found
CMake Error at /.conda/envs/draco/share/cmake-3.21/Modules/FindPkgConfig.cmake:554 (message):
  A required package was not found
Call Stack (most recent call first):
  /.conda/envs/draco/share/cmake-3.21/Modules/FindPkgConfig.cmake:776 (_pkg_check_modules_internal)
  CMakeLists.txt:32 (pkg_check_modules)


-- Configuring incomplete, errors occurred!

Any idea how to proceed? Is the dlib-1 problem related to dlib?

**Comment by dincarnato** [comment]
Did you compile and install dlib? Here is a tutorial to help you with that: https://learnopencv.com/install-dlib-on-ubuntu/

**Comment by sjhuang6** [comment]
I used "conda install -c conda-forge dlib", and here is the version:
dlib                      19.22.0          py36h446f8a6_0    conda-forge

**Comment by dincarnato** [comment]
You might want to try installing it from source.

**Comment by sjhuang6** [comment]
yes install dlib from source works! Thanks Danny,

**Comment by dincarnato** [comment]
Great!
