### ISSUE TITLE
Merge mutation map (MM) files?

### ISSUE THREAD

**Issue by nickforino** [dincarnato/RNAFramework#16]
Hi Danny,

Is merging of mm files a planned feature?

I'm in a scenario where I plan to use DRACO on a large target that I've tiled across when making my library, which is making the way I use mask files during counting a bit complicated.

Usually, I map reads from each 'tile' of my target, run rf-count on for bam for each tile with its appropriate mask file, then merge the final RC files together. However, since mm files are generated at the counting step, I appear to be forced into merging bam files prior to counting. This introduces the following issue: some alignment positions in the merged bam will have a mixture of wildtype sequence (due to primer binding in one 'tile') and bona fide mutational signal (from an overlapping 'tile).

 If I was able to merge mm files, I could count each of my bams seperately with their appropriate mask, then merge everything together for DRACO. Any advice you have would be greatly appreciated, and let me know if you need any clarification with my question.

Best,
Nick

**Comment by dincarnato** [comment]
Hi Nick,

This is something we did not originally plan. Also, at present, the mask file is only affecting the RC file, but not the MM file. I should look into this, and get back to you.

Best,
Danny

**Comment by nickforino** [comment]
Thanks for the quick reply, Danny.
Sounds good, thank you for looking into this.

Best,
Nick

**Comment by dincarnato** [comment]
Hi Nick,

I have now updated rf-count to apply the mask also to the MM files.
Furthermore, please find attached a small script that will allow you to combine MM files from different rf-count runs.
Usage is very simple:

./combine_mm <output file> <input1.mm> <input2.mm> ... <inputn.mm>

The scripts expects to find in the same folder as the MM files also an index file with the same filename, but the .mmi extension (this is automatically generated by rf-count at runtime).

Hope this helps!
Best,

Danny

[combine_mm.zip](https://github.com/dincarnato/RNAFramework/files/7185344/combine_mm.zip)

**Comment by nickforino** [comment]
Hi Danny,

The script works like a charm, this enables me to do DRACO experiments now.
Thank you for your amazing support, Danny!

Cheers,
Nick
