### ISSUE TITLE
rf-norm won't pick up configuration file if -c option is not the first one that is specified

### ISSUE THREAD

**Issue by coffeebond** [dincarnato/RNAFramework#17]
It seems if -c option is not placed as the first option in the command for rf-norm, the configuration file won't be picked up by the program and the output won't give a warning about this. I think it uses default configuration in this case. 

For example, the following will be fine
rf-norm -c configuration.txt -p 20 ....

But if the position of -p and -c are swapped like this:
rf-norm -p 20 -c configuration.txt 
The program won't use anything in the configuration file.

**Comment by dincarnato** [comment]
Hi coffeebond, 

this should definitely not be happening.
I will look into this and get back to you.

Best,
Danny

**Comment by dincarnato** [comment]
Hi coffeebond,

can you please try to pull and let me know if it's fixed?

Best,
Danny

**Comment by coffeebond** [comment]
Thanks. I think it's working as expected now.

I've got another question and I will ask you in a different thread.
