### ISSUE TITLE
rf-norm failed compilation

### ISSUE THREAD

**Issue by xiefzh** [dincarnato/RNAFramework#2]
rf-count and rf-rctools worked out fine. But when I use rf-norm, I got error like below:

$ rf-norm -h
Bareword found where operator expected at /home/xiefz/RNAseq_tool/RNAFramework-master/lib/RF/Config.pm line 32, near "s/^default.//r"
syntax error at /home/xiefz/RNAseq_tool/RNAFramework-master/lib/RF/Config.pm line 32, near "s/^default.//r"
Global symbol "$class" requires explicit package name at /home/xiefz/RNAseq_tool/RNAFramework-master/lib/RF/Config.pm line 36.
Global symbol "%parameters" requires explicit package name at /home/xiefz/RNAseq_tool/RNAFramework-master/lib/RF/Config.pm line 36.
Global symbol "%parameters" requires explicit package name at /home/xiefz/RNAseq_tool/RNAFramework-master/lib/RF/Config.pm line 51.
syntax error at /home/xiefz/RNAseq_tool/RNAFramework-master/lib/RF/Config.pm line 62, near "}"
syntax error at /home/xiefz/RNAseq_tool/RNAFramework-master/lib/RF/Config.pm line 95, near "}"
syntax error at /home/xiefz/RNAseq_tool/RNAFramework-master/lib/RF/Config.pm line 107, near ""ACGT" : join("", sort(uniq(iupac2nt(rna2dna($self->{reactivebases})))))"
syntax error at /home/xiefz/RNAseq_tool/RNAFramework-master/lib/RF/Config.pm line 111, near "}"
syntax error at /home/xiefz/RNAseq_tool/RNAFramework-master/lib/RF/Config.pm line 170, near "}"
syntax error at /home/xiefz/RNAseq_tool/RNAFramework-master/lib/RF/Config.pm line 206, near "}"
/home/xiefz/RNAseq_tool/RNAFramework-master/lib/RF/Config.pm has too many errors.
Compilation failed in require at /home/xiefz/RNAseq_tool/RNAFramework-master/rf-norm line 34.
BEGIN failed--compilation aborted at /home/xiefz/RNAseq_tool/RNAFramework-master/rf-norm line 34.

**Comment by dincarnato** [comment]
Hi xiefzh,
Could you please tell me which version have you installed?
Have you updated to the latest release by "git pull"?
Best,
Danny

**Comment by xiefzh** [comment]
Hi Danny, 
I've tried "git pull",but the problem remains.

**Comment by dincarnato** [comment]
Hi xiefzh,
it works without any issue on both my server and laptop. I also made a colleague of mine test it and it worked.
Can you also please compress the RNAFramework folder you got from git and send it to me?

Danny

**Comment by xiefzh** [comment]
[RNAFramework.zip](https://github.com/dincarnato/RNAFramework/files/2702134/RNAFramework.zip)
Hi Danny,

I got a very busy friday. 
Sorry for my delayed reply. 

Xiefzh

**Comment by dincarnato** [comment]
I checked and our versions are identical.
I am thinking of an issue with the perl interpreter.
Can you please paste the result of the following command:

/usr/bin/env perl --version

**Comment by xiefzh** [comment]
[xiefz@master-sysu ~]$ /usr/bin/env perl --version

This is perl, v5.10.1 (*) built for x86_64-linux-thread-multi

Copyright 1987-2009, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

Thanks. 
Since I don`t have the root access, I got the local::lib, would this affects?

**Comment by dincarnato** [comment]
Wow! Your Perl installation is quite old.
I recommend you to install a newer version of Perl (maybe you can ask to your sysadmin to help you with that).
I have never tested the RNA Framework with Perl versions < 5.18.
Do you have a Mac/Linux PC with a more recent Perl version that you can use to test the installation?

**Comment by dincarnato** [comment]
Ok, keep me updated.

**Comment by xiefzh** [comment]
Hi Danny, 
I have tried it with Perl 5.22.0 and it worked out fine.
Merry Christmas.(maybe a little bit late?)
Thank you for your help.
And i think this issue can be closed.

**Comment by dincarnato** [comment]
Hi xiefzh,
This is great! I will anyway look into the issue as soon as I have time to install an older Perl version.
In the meantime, Merry Christmas and a Happy New Year too.

Danny
