### ISSUE TITLE
java.lang.module.FindException: Module javafx.controls not found

### ISSUE THREAD

**Issue by amir-tagh** [dincarnato/RNAFramework#21]
Hello,

I am trying to launch the RNArtist in Ubuntu 18 and I am getting the following error message: 
(openjdk 11.0.14 2022-01-18)

I googled the problem but could't find a solution, any idea how can I solve this.

Thanks for your help.

Best,
Amir

$ ./launch_rnartist_for_Linux.sh
Error occurred during initialization of boot layer
java.lang.module.FindException: Module javafx.controls not found

**Comment by dincarnato** [comment]
Dear Amir,

This is the git repo of RNAFramework, not RNArtist. You are posting the question on the wrong repo.

Best,
Dannh

**Comment by amir-tagh** [comment]
Hello Danny,

My apologies, thanks.

Best,
Amir
