### ISSUE TITLE
rf-json2rc  --extend parameter omits terminal nucleotide of reference sequence

### ISSUE THREAD

**Issue by nickforino** [dincarnato/RNAFramework#22]
Hi Danny,

I'm hoping you're well.
Upon inspecting the .rc output after invoking rf-json2rc using the --extend parameter, the final nucleotide of the reference sequence is omitted. This is true even if the the extension amount is artificially high (eg. 500 nucleotides).

All the best,
Nick

**Comment by dincarnato** [comment]
Hi Nick,

this was a tricky one to spot! Thanks for reporting it.
Fixed, just git pull. Let me know if everything looks fine.

Best,
Danny
