### ISSUE TITLE
1 folding failed

### ISSUE THREAD

**Issue by liangyi521** [dincarnato/RNAFramework#24]
Dear Danny, 
When working with my yeast data, the tools were pretty smooth, up until the rf-fold step. Whether I enter the separate xml file or the combine xml file, the result is failure.

rf-fold yeast_dms_1_norm/NR_132222.1\:\:chrXII\:465069-466869.xml
[+] Checking method's requirements...
[+] Making output directory tree...
[+] Importing XML file(s) [1 imported]
[+] Folding RNA structures [Last: none]
[+] Folding statistics:

  [*] Folded transcripts:    0
  [*] Discarded transcripts: 1 total
                             0 XML parsing failed
                             0 constraint file generation failed
                             0 FASTA file generation failed
                             1 folding failed
                             0 I/O error

[+] All done.

Best,
yiliang

**Comment by dincarnato** [comment]
Hello Yiliang,

I have a hunch that the presence of colon chars in the transcript name/id (those "::") might drive Vienna RNAfold crazy.
Can you please try to rename the file to NR_132222.1_chrXII:465069-466869 and to also replace the "::" with a "_" in the id field of the XML file, and try again?

Thanks.
Best,
Danny

**Comment by liangyi521** [comment]
Dear Danny,

Thank you for your reply, I replaced "::" for "_", as shown below, still failed.

rf-fold NR_132222.1_chrXII_465069-466869.xml 

[+] Checking method's requirements...
[+] Making output directory tree...
[+] Importing XML file(s) [1 imported]
[+] Folding RNA structures [Last: none]
[+] Folding statistics:

  [*] Folded transcripts:    0
  [*] Discarded transcripts: 1 total
                             0 XML parsing failed
                             0 constraint file generation failed
                             0 FASTA file generation failed
                             1 folding failed
                             0 I/O error

Best,
yiliang

**Comment by liangyi521** [comment]
Hello Danny, 


Attached are my input and output files, and my command is
rf-fold -KT NR_132222.1_chrXII_465069-466869.xml


Yiliang




在 2022-10-26 10:02:45，"Danny Incarnato" ***@***.***> 写道：

Please show the command you are executing. Also, try to rerun the same command adding the -KT parameter and share the content of the output folder.

Danny

**Comment by dincarnato** [comment]
I don't see any attachment

**Comment by liangyi521** [comment]
Dear Danny,

After running `rf-fold -KT NR_132222.1_chrXII_465069-466869.xml`, I got a tmp folder, including 3 files.

1. NR_132222.1_chrXII:465069-466869_0-1799_1.fa

$cat NR_132222.1_chrXII:465069-466869_0-1799_1.fa
>NR_132222.1_chrXII:465069-466869_0-1799_1
TATCTGGTTGATCCTGCCAGTAGTCATATGCTTGTCTCAAAGATTAAGCCATGCATGTCTAAGTATAAGCAATTTATACAGTGAAACTGCGAATGGCTCATTAAATCAGTTATCGTTTATTTGATAGTTCCTTTACTACATGGTATAACTGTGGTAATTCTAGAGCTAATACATGCTTAAAATCTCGACCCTTTGGAAGAGATGTATTTATTAGATAAAAAATCAATGTCTTCGGACTCTTTGATGATTCATAATAACTTTTCGAATCGCATGGCCTTGTGCTGGCGATGGTTCATTCAAATTTCTGCCCTATCAACTTTCGATGGTAGGATAGTGGCCTACCATGGTTTCAACGGGTAACGGGGAATAAGGGTTCGATTCCGGAGAGGGAGCCTGAGAAACGGCTACCACATCCAAGGAAGGCAGCAGGCGCGCAAATTACCCAATCCTAATTCAGGGAGGTAGTGACAATAAATAACGATACAGGGCCCATTCGGGTCTTGTAATTGGAATGAGTACAATGTAAATACCTTAACGAGGAACAATTGGAGGGCAAGTCTGGTGCCAGCAGCCGCGGTAATTCCAGCTCCAATAGCGTATATTAAAGTTGTTGCAGTTAAAAAGCTCGTAGTTGAACTTTGGGCCCGGTTGGCCGGTCCGATTTTTTCGTGTACTGGATTTCCAACGGGGCCTTTCCTTCTGGCTAACCTTGAGTCCTTGTGGCTCTTGGCGAACCAGGACTTTTACTTTGAAAAAATTAGAGTGTTCAAAGCAGGCGTATTGCTCGAATATATTAGCATGGAATAATAGAATAGGACGTTTGGTTCTATTTTGTTGGTTTCTAGGACCATCGTAATGATTAATAGGGACGGTCGGGGGCATCAGTATTCAATTGTCAGAGGTGAAATTCTTGGATTTATTGAAGACTAACTACTGCGAAAGCATTTGCCAAGGACGTTTTCATTAATCAAGAACGAAAGTTAGGGGATCGAAGATGATCAGATACCGTCGTAGTCTTAACCATAAACTATGCCGACTAGGGATCGGGTGGTGTTTTTTTAATGACCCACTCGGCACCTTACGAGAAATCAAAGTCTTTGGGTTCTGGGGGGAGTATGGTCGCAAGGCTGAAACTTAAAGGAATTGACGGAAGGGCACCACCAGGAGTGGAGCCTGCGGCTTAATTTGACTCAACACGGGGAAACTCACCAGGTCCAGACACAATAAGGATTGACAGATTGAGAGCTCTTTCTTGATTTTGTGGGTGGTGGTGCATGGCCGTTCTTAGTTGGTGGAGTGATTTGTCTGCTTAATTGCGATAACGAACGAGACCTTAACCTACTAAATAGTGGTGCTAGCATTTGCTGGTTATCCACTTCTTAGAGGGACTATCGGTTTCAAGCCGATGGAAGTTTGAGGCAATAACAGGTCTGTGATGCCCTTAGACGTTCTGGGCCGCACGCGCGCTACACTGACGGAGCCAGCGAGTCTAACCTTGGCCGAGAGGTCTTGGTAATCTTGTGAAACTCCGTCGTGCTGGGGATAGAGCATTGTAATTATTGCTCTTCAACGAGGAATTCCTAGTAAGCGCAAGTCATCAGCTTGCGTTGATTACGTCCCTGCCCTTTGTACACACCGCCCGTCGCTAGTACCGATTGAATGGCTTAGTGAGGCCTCAGGATCTGCTTAGAGAAGGGGGCAACTCCATCTCAGAGCGGAGAATTTGGACAAACTTGGTCATTTAGAGGAACTAAAAGTCGTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATCATTA
........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

2. NR_132222.1_chrXII_465069-466869_0-1799_1.fold 

$cat NR_132222.1_chrXII_465069-466869_0-1799_1.fold 
>NR_132222.1_chrXII:465069-466869_0-1799_1
UAUCUGGUUGAUCCUGCCAGUAGUCAUAUGCUUGUCUCAAAGAUUAAGCCAUGCAUGUCUAAGUAUAAGCAAUUUAUACAGUGAAACUGCGAAUGGCUCAUUAAAUCAGUUAUCGUUUAUUUGAUAGUUCCUUUACUACAUGGUAUAACUGUGGUAAUUCUAGAGCUAAUACAUGCUUAAAAUCUCGACCCUUUGGAAGAGAUGUAUUUAUUAGAUAAAAAAUCAAUGUCUUCGGACUCUUUGAUGAUUCAUAAUAACUUUUCGAAUCGCAUGGCCUUGUGCUGGCGAUGGUUCAUUCAAAUUUCUGCCCUAUCAACUUUCGAUGGUAGGAUAGUGGCCUACCAUGGUUUCAACGGGUAACGGGGAAUAAGGGUUCGAUUCCGGAGAGGGAGCCUGAGAAACGGCUACCACAUCCAAGGAAGGCAGCAGGCGCGCAAAUUACCCAAUCCUAAUUCAGGGAGGUAGUGACAAUAAAUAACGAUACAGGGCCCAUUCGGGUCUUGUAAUUGGAAUGAGUACAAUGUAAAUACCUUAACGAGGAACAAUUGGAGGGCAAGUCUGGUGCCAGCAGCCGCGGUAAUUCCAGCUCCAAUAGCGUAUAUUAAAGUUGUUGCAGUUAAAAAGCUCGUAGUUGAACUUUGGGCCCGGUUGGCCGGUCCGAUUUUUUCGUGUACUGGAUUUCCAACGGGGCCUUUCCUUCUGGCUAACCUUGAGUCCUUGUGGCUCUUGGCGAACCAGGACUUUUACUUUGAAAAAAUUAGAGUGUUCAAAGCAGGCGUAUUGCUCGAAUAUAUUAGCAUGGAAUAAUAGAAUAGGACGUUUGGUUCUAUUUUGUUGGUUUCUAGGACCAUCGUAAUGAUUAAUAGGGACGGUCGGGGGCAUCAGUAUUCAAUUGUCAGAGGUGAAAUUCUUGGAUUUAUUGAAGACUAACUACUGCGAAAGCAUUUGCCAAGGACGUUUUCAUUAAUCAAGAACGAAAGUUAGGGGAUCGAAGAUGAUCAGAUACCGUCGUAGUCUUAACCAUAAACUAUGCCGACUAGGGAUCGGGUGGUGUUUUUUUAAUGACCCACUCGGCACCUUACGAGAAAUCAAAGUCUUUGGGUUCUGGGGGGAGUAUGGUCGCAAGGCUGAAACUUAAAGGAAUUGACGGAAGGGCACCACCAGGAGUGGAGCCUGCGGCUUAAUUUGACUCAACACGGGGAAACUCACCAGGUCCAGACACAAUAAGGAUUGACAGAUUGAGAGCUCUUUCUUGAUUUUGUGGGUGGUGGUGCAUGGCCGUUCUUAGUUGGUGGAGUGAUUUGUCUGCUUAAUUGCGAUAACGAACGAGACCUUAACCUACUAAAUAGUGGUGCUAGCAUUUGCUGGUUAUCCACUUCUUAGAGGGACUAUCGGUUUCAAGCCGAUGGAAGUUUGAGGCAAUAACAGGUCUGUGAUGCCCUUAGACGUUCUGGGCCGCACGCGCGCUACACUGACGGAGCCAGCGAGUCUAACCUUGGCCGAGAGGUCUUGGUAAUCUUGUGAAACUCCGUCGUGCUGGGGAUAGAGCAUUGUAAUUAUUGCUCUUCAACGAGGAAUUCCUAGUAAGCGCAAGUCAUCAGCUUGCGUUGAUUACGUCCCUGCCCUUUGUACACACCGCCCGUCGCUAGUACCGAUUGAAUGGCUUAGUGAGGCCUCAGGAUCUGCUUAGAGAAGGGGGCAACUCCAUCUCAGAGCGGAGAAUUUGGACAAACUUGGUCAUUUAGAGGAACUAAAAGUCGUAACAAGGUUUCCGUAGGUGAACCUGCGGAAGGAUCAUUA
........((((((((((((((((..(((((((((((...))).))))).)))(((((.(((((.......))))).)).)))..)))))...))))......((((.((((.((...((((..((((((((((((((((.(......)))))))))........((((((.((((.....(((((..((....))..))))))))).)))))).......(((((.(((....)))...)))))(((((..((.....))..)))))((...))...(((((((((((((..............(((((....((((....((((((((.......)))))))))))).....))))).(((((.((((((((....(((((((...((((((........)))).))...)))..))))..((((((((((((..((((((...((((......)))))))))).......(((((((.((((((((((....))))))))))((((.........)))).......((((...))))....(((((((.......((((((((.((....))))))...)))))))))))..))).))))...((((((((((((((((((.(((....))).))))((((((.((((((((((((((.....))).).)))))....))))).))))))....((((((.(..((..(((.((....)))))..))..).))))))....((((((((.....))))))))......(((((((.(((((((.....(((((........)))))(((((((((.....)))))))))..(((((((((..(((..((((..((((((((.(((((.(((...((((..(((.((((((.(((.((((......)))).)))..)))))).)))......(((....)))..))))...)))))))).))))))).)..))))..))).))))))))).((((.........))))(((((.(((....))))))))((((((((((..((((((((.(((........)))))))))))..(((..(.((((.(((((...))))).)))).))))((((.(((((....)))))..)))).........(((((..(.((((((((..((((.(((((...))))).))))..(((.....)))...(((((((((.(((...........))))))..((((((((((....)))))))))).)))))))))))))).)..))))))))))))))).))))))).))))))))))))))))))))).....((((((...(((.((((..(((((.((((((....))))))...)))))..)))))))..(((((((((...)))))))))..(((.........)))))))))(((..((((..(((...)))))))..))))))))))....((((((((...(((((....(((..((((....))))..)))...)))))....)))))))))))))(((((((((((.((....)).))))))......(((....))).((((((((((((.....))))))))...))))))))).)))))).)).).).))).)))))))))))))...((((((((((.(((....((......(((((((.((((.((((....)))).)))).)))))))......))....))).)))))))))))))))))).))))))))))..))))((((((((....)))))))))))))))... (-896.71)
>NR_132222.1_chrXII:465069-466869_0-1799_1
UAUCUGGUUGAUCCUGCCAGUAGUCAUAUGCUUGUCUCAAAGAUUAAGCCAUGCAUGUCUAAGUAUAAGCAAUUUAUACAGUGAAACUGCGAAUGGCUCAUUAAAUCAGUUAUCGUUUAUUUGAUAGUUCCUUUACUACAUGGUAUAACUGUGGUAAUUCUAGAGCUAAUACAUGCUUAAAAUCUCGACCCUUUGGAAGAGAUGUAUUUAUUAGAUAAAAAAUCAAUGUCUUCGGACUCUUUGAUGAUUCAUAAUAACUUUUCGAAUCGCAUGGCCUUGUGCUGGCGAUGGUUCAUUCAAAUUUCUGCCCUAUCAACUUUCGAUGGUAGGAUAGUGGCCUACCAUGGUUUCAACGGGUAACGGGGAAUAAGGGUUCGAUUCCGGAGAGGGAGCCUGAGAAACGGCUACCACAUCCAAGGAAGGCAGCAGGCGCGCAAAUUACCCAAUCCUAAUUCAGGGAGGUAGUGACAAUAAAUAACGAUACAGGGCCCAUUCGGGUCUUGUAAUUGGAAUGAGUACAAUGUAAAUACCUUAACGAGGAACAAUUGGAGGGCAAGUCUGGUGCCAGCAGCCGCGGUAAUUCCAGCUCCAAUAGCGUAUAUUAAAGUUGUUGCAGUUAAAAAGCUCGUAGUUGAACUUUGGGCCCGGUUGGCCGGUCCGAUUUUUUCGUGUACUGGAUUUCCAACGGGGCCUUUCCUUCUGGCUAACCUUGAGUCCUUGUGGCUCUUGGCGAACCAGGACUUUUACUUUGAAAAAAUUAGAGUGUUCAAAGCAGGCGUAUUGCUCGAAUAUAUUAGCAUGGAAUAAUAGAAUAGGACGUUUGGUUCUAUUUUGUUGGUUUCUAGGACCAUCGUAAUGAUUAAUAGGGACGGUCGGGGGCAUCAGUAUUCAAUUGUCAGAGGUGAAAUUCUUGGAUUUAUUGAAGACUAACUACUGCGAAAGCAUUUGCCAAGGACGUUUUCAUUAAUCAAGAACGAAAGUUAGGGGAUCGAAGAUGAUCAGAUACCGUCGUAGUCUUAACCAUAAACUAUGCCGACUAGGGAUCGGGUGGUGUUUUUUUAAUGACCCACUCGGCACCUUACGAGAAAUCAAAGUCUUUGGGUUCUGGGGGGAGUAUGGUCGCAAGGCUGAAACUUAAAGGAAUUGACGGAAGGGCACCACCAGGAGUGGAGCCUGCGGCUUAAUUUGACUCAACACGGGGAAACUCACCAGGUCCAGACACAAUAAGGAUUGACAGAUUGAGAGCUCUUUCUUGAUUUUGUGGGUGGUGGUGCAUGGCCGUUCUUAGUUGGUGGAGUGAUUUGUCUGCUUAAUUGCGAUAACGAACGAGACCUUAACCUACUAAAUAGUGGUGCUAGCAUUUGCUGGUUAUCCACUUCUUAGAGGGACUAUCGGUUUCAAGCCGAUGGAAGUUUGAGGCAAUAACAGGUCUGUGAUGCCCUUAGACGUUCUGGGCCGCACGCGCGCUACACUGACGGAGCCAGCGAGUCUAACCUUGGCCGAGAGGUCUUGGUAAUCUUGUGAAACUCCGUCGUGCUGGGGAUAGAGCAUUGUAAUUAUUGCUCUUCAACGAGGAAUUCCUAGUAAGCGCAAGUCAUCAGCUUGCGUUGAUUACGUCCCUGCCCUUUGUACACACCGCCCGUCGCUAGUACCGAUUGAAUGGCUUAGUGAGGCCUCAGGAUCUGCUUAGAGAAGGGGGCAACUCCAUCUCAGAGCGGAGAAUUUGGACAAACUUGGUCAUUUAGAGGAACUAAAAGUCGUAACAAGGUUUCCGUAGGUGAACCUGCGGAAGGAUCAUUA
........((((((((((((((((..(((((((((((...))).))))).)))(((((.(((((.......))))).)).)))..)))))...))))......((((.((((.((...((((..((((((((((((((((.(......)))))))))........((((((.((((.....(((((..((....))..))))))))).)))))).......(((((.(((....)))...)))))(((((..((.....))..)))))((...))...(((((((((((((..............(((((....((((....((((((((.......)))))))))))).....))))).(((((.((((((((....(((((((...((((((........)))).))...)))..))))..((((((((((((..((((((...((((......)))))))))).......(((((((.((((((((((....))))))))))((((.........)))).......((((...))))....(((((((.......((((((((.((....))))))...)))))))))))..))).))))...((((((((((((((((((.(((....))).))))((((((.((((((((((((((.....))).).)))))....))))).))))))....((((((.(..((..(((.((....)))))..))..).))))))....((((((((.....))))))))......(((((((.(((((((.....(((((........)))))(((((((((.....)))))))))..(((((((((..(((..((((..((((((((.(((((.(((...((((..(((.((((((.(((.((((......)))).)))..)))))).)))......(((....)))..))))...)))))))).))))))).)..))))..))).))))))))).((((.........))))(((((.(((....))))))))((((((((((..((((((((.(((........)))))))))))..(((..(.((((.(((((...))))).)))).))))((((.(((((....)))))..)))).........(((((..(.((((((((..((((.(((((...))))).))))..(((.....)))...(((((((((.(((...........))))))..((((((((((....)))))))))).)))))))))))))).)..))))))))))))))).))))))).))))))))))))))))))))).....((((((...(((.((((..(((((.((((((....))))))...)))))..)))))))..(((((((((...)))))))))..(((.........)))))))))(((..((((..(((...)))))))..))))))))))....((((((((...(((((....(((..((((....))))..)))...)))))....)))))))))))))(((((((((((.((....)).))))))......(((....))).((((((((((((.....))))))))...))))))))).)))))).)).).).))).)))))))))))))...((((((((((.(((....((......(((((((.((((.((((....)))).)))).)))))))......))....))).)))))))))))))))))).))))))))))..))))((((((((....)))))))))))))))... (-896.71)

3. NR_132222.1_chrXII:465069-466869_0-1799_1.shape
This file is too long to display.

Can I consider the .fold file already a constraint file? 
In fact, entering both the .fa file and the .fold file into the web version of RNAfold also failed, warning a constraint file error/unavailability.

yiliang

**Comment by dincarnato** [comment]
I see you still have one of the “:” in the id field in the XML file.
Can you please try with the amended XML file?

**Comment by dincarnato** [comment]
I tried by removing the ":" you missed, and the file works fine for me.
I will add a check to remove invalid characters that might make RNAfold crash in the next release.
Please let me know if i can close the issue.

Danny

**Comment by liangyi521** [comment]
Great! After I removed all the ":", the file works fine. 
It would be nice to get it fixed in the next version.
Thank you again.

Yiliang
