### ISSUE TITLE
Splicing bug when running rf-json2rc module

### ISSUE THREAD

**Issue by anaveira4** [dincarnato/RNAFramework#25]
To whom it may concern:

I am trying to run the rf-json2rc module to process DRACO output (as .json) files and I have validated that the length of the windows in the json file (as given by the start and end keys in each window) match the length of the count and coverage arrays in that window. However, I am still consistently getting the following error when running the rf-json2rc module:

![image](https://user-images.githubusercontent.com/118499807/207970814-2d349c5b-886f-4526-bee2-99706ab286aa.png)

It seems as though the length of the counts array (the number to the left of the '!=' sign) is consistently one larger than it should be. The length of the sequence matches the length of the window that I see in the json file but for some reason, the counts and coverages arrays are getting parsed with an extra item inside (though it is not consistently an offset of 1). 

Thank you in advance for your help!

**Comment by dincarnato** [comment]
Hi anaveira4,

To investigate the issue I will need the json and rc files.
Would you be able to share them?

Best, 
Danny

**Comment by anaveira4** [comment]
Hi Danny,

Thank you for your help. I would be happy to share the corresponding files. What is the easiest way to send those over?

Best,
-Alberto

**Comment by dincarnato** [comment]
You should be able to attach them to the reply here on github, or alternatively just mail them to me at: dincarnato@incarnatolab.com

**Comment by dincarnato** [comment]
Hi Alberto,

I don't seem to be able to reproduce the issue when running the command.
When was the last time you issued a git pull on RNAFramework? It looks like you might be behind with your updates.
Please try and let me know.

All the best,
Danny

**Comment by anaveira4** [comment]
Hi Danny,

You were 100% correct. Should have started with that. Thank you for your help though.

Best,
-Alberto
