### ISSUE TITLE
RNAFramework inside of conda environments?

### ISSUE THREAD

**Issue by Kobie-Kirven** [dincarnato/RNAFramework#28]
Hi there,

I have found the RNAFramework tools very useful, but I am wondering if it's possible to add functionality for those interested in running the tools inside of a conda environment where dependencies like bowtie2 might not necessarily be in the path. I use Snakemake for a lot of my analysis, and I create conda environments for rules or and sets of rules for reproducibility purposes. I have found a workaround for RNAFramework where I supply the path to the executable for the particular dependency inside of the conda environment created by Snakemake, but it's kind of hacky. 

Thank you.

**Comment by dincarnato** [comment]
Hi Kobie-Kirven,

thanks for your message and for using RNAFramework.
Are you using the --bowtie /path/to/bowtie parameter of the rf-map to do this?

Best,
Danny

**Comment by Kobie-Kirven** [comment]
Hi Danny,

Yes, that's how I was able to get it to work. Snakemake gives random names for the conda environments it creates, but for me, accessing bowtie2 looked something like:
  --bowtie .snakemake/conda/ade61af89ca3c983de90df966b8449ec_/bin/bowtie2

If I were to activate that environment, I could run bowtie2 as if it were in my PATH, but it's only contained inside that environment. From what I understand, rf-map checks that the necessary tool is in your path or you have the option to supply the path to the particular executable. For running inside a conda env, it would be cool if the program checked that bowtie2 was installed rather than installed in PATH. 

Thank you for your help!
Kobie.

**Comment by dincarnato** [comment]
What RNAFramework is essentially a "which bowtie2". What happens if you run that command within your conda environment?
