### ISSUE TITLE
Experiencing trouble with rf-rctools merge

### ISSUE THREAD

**Issue by Asperatus22** [dincarnato/RNAFramework#29]
Hi, 
Thanks for the works.
While trying to merge two rc file with rf-rctools merge :

rf-rctools merge \
  -o rf_count_merge_NM/NM_merge.rc -ow \
  -i ./rf_count_fusion_impair_NM/index.rci,./rf_count_fusion_pair_NM/index.rci \               # tryed with ./ and without
  rf_count_fusion_impair_NM/19-190123.rc rf_count_fusion_pair_NM/20-190123.rc

i have this error :
[!] Error: Provided RCI index file "rf_count_fusion_impair_DMS/index.rci,rf_count_fusion_pair_DMS/index.rci" does not exist

Maybe an argument parsing error ?

while i try to run the code with only one argument for the index : 
rf-rctools merge \
  -o rf_count_merge_NM/NM_merge.rc -ow \
  -i ./rf_count_fusion_impair_NM/index.rci \                                                                            # tryed with ./ and without
  rf_count_fusion_impair_NM/19-190123.rc rf_count_fusion_pair_NM/20-190123.rc

i run into this error : 
[!] Exception [RF::Data::IO::RC->new()]:
    No such file or directory
    -> Caught at /nfs/bin/RNAFramework/lib/Core/Base.pm line 126.

any kind of help would be appréciate.
Best regards
Lionel

**Comment by dincarnato** [comment]
Hi Lionel,

hard for me to understand what is going on.
I have a hunch: does the rf_count_merge_NM folder exist? Cause rf-rctools merge won't generate it in case it doesn't.

Can you please send over the files so that I can try?
You can send them to my email: dincarnato@rnaframework.com

Best,
Danny

**Comment by Asperatus22** [comment]
the rf_count_merge_NM folder didn't exist.

I added a "check and create folder" in my code and the code run well, but only with a unique .rci file.
This could be a code improvement or a documentation warning.

I still encounter the first error with multiple .rci
Do you still need my file to test with ?

Thank you for your help and reactivity.

**Comment by dincarnato** [comment]
Ohhh, now I see the issue!
Yes, please try to git pull and let me know if this solves.

Best,
Danny

**Comment by Asperatus22** [comment]
Yess, it works well.
Thanks a lot
Lionel

**Comment by dincarnato** [comment]
If all your samples are generated from the same reference, even if through different rf-count runs, the resulting index.rci files will be absolutely identical. Then you can simply pass any one index.rci via the -i parameter, no need for renaming.
