### ISSUE TITLE
FASTA header parsing check

### ISSUE THREAD

**Issue by ababaian** [dincarnato/RNAFramework#3]
Hey Danny,

Small error I ran into. It's non-critical but I think it can be fixed with a FASTA header check pre-alignment.

I have a small RNA reference fasta file I'm using with RNAframework. Some of the names of the fasta entries contained "/" characters as they were taken from a database. I checked the SAM specification and this is technically OK as it matches the regex: `[0-9A-Za-z!#$%&+./:;?@^_|~-][0-9A-Za-z!#$%&*+./:;=?@^_|~-]*`

When generating `xml` or `svg` output, once a seqname with that header is reached all subsequent contigs are not processed. When I run `rf-peakcall` with the following command I get an error.

```
artem@glitch[RNAframework3] ./rf-peakcall -p 1 \                                                         [ 5:24PM]
   -c prima_sRNA_count/input_pA_ko1.rc\
   -I prima_sRNA_count/prima_pA_ko1.rc\
   -i prima_sRNA_count/input_pA_ko1.rci,prima_sRNA_count/prima_pA_ko1.rci\
   -mc 0 -w 15\
   -g -mp -e 2 -s -o peaks/ko1

[+] Making output directory...
[+] Loading transcript IDs... 2411 transcripts loaded.
[+] Calling peaks [Last: mgU12-22/U4-8]Thread 1 terminated abnormally:
[!] Exception [main->call()]:
    No such file or directory
    -> Caught at /home/artem/Capilano/RNAframework3/lib/Core/Base.pm line 126 thread 1.

[+] Sorting peaks...
[+] Writing output BED file...
[0!] Exception [main->plotcoverage()]:
    Values array is empty
    -> Caught at /home/artem/Capilano/RNAframework3/lib/Core/Mathematics.pm line 260.
```

I would suggest adding a REGEX check of FASTA file headers to exclude special characters, perhaps matching only : `[0-9A-Za-z_-].*` so as not to cause issues in creating files downstream. I'm willing to implement this if it's something you would like to add, otherwise documenting is a good solution for the mean while.

**Comment by dincarnato** [comment]
Hi ababaian,

many thanks for reporting the bug.
The issue is now solved.

Best,

Danny
