### ISSUE TITLE
-smp use in rf-fold

### ISSUE THREAD

**Issue by Asperatus22** [dincarnato/RNAFramework#33]
Hi all,
i notice a possible issue in rf-fold:
In the help, it is notice that -smp version of RNA structure  would be use by default if available, but it does'nt use this -smp version in my config, despite the presence of the two version :

(RNAframework) []$ which ShapeKnots
/nfs/conda/envs/RNAframework/bin/ShapeKnots

(RNAframework) []$ which ShapeKnots-smp
/nfs/conda/envs/RNAframework/bin/ShapeKnots-smp

when i run rf-fold on my server, it run ShapeKnots

I create a .pl test file with the folowing script : (i'm not aware of Perl langage...)

#!/usr/bin/env perl

use strict;
use Config;
use Cwd;
use File::Basename;
use File::Which;
use File::Path qw(mkpath);
use File::Spec;
use FindBin qw($Bin);
use Getopt::Long qw(:config no_ignore_case);
use POSIX qw(floor);
use threads;
use threads::shared;

use lib $Bin . "/lib";

use constant MINWINLENGTH => 50; # Minimum window length for windowed folding
my($shapeknots) ;

$shapeknots = File::Spec->rel2abs($shapeknots || which("ShapeKnots"|| which("ShapeKnots-smp") ));  #from line 198 in rf-fold script

print $shapeknots

it return:
>/nfs/conda/envs/RNAframework/bin/ShapeKnots

notice that i need to add use File::Which; 

if i invert the order of the Which it print ShapeKnot-smp.

it should be the same problem with "Fold", in line 197 and "partition" in line 199

best regards

Lionel

**Comment by dincarnato** [comment]
Hi Lionel,

thanks for reporting!
Indeed, this was changed some time ago for tests and I forgot to change it back.
It should be fixed now. Please issue a git pull.

All the best,
Danny

**Comment by Asperatus22** [comment]
Hi Danny
i think the problème is back this the correction you made on 31 of jully on rf-fold.
thanks for your work
Lionel

**Comment by dincarnato** [comment]
Yes, I'm aware, will release the new RNAFramework later today with that fix included

**Comment by dincarnato** [comment]
You can git pull v2.8.4
