### ISSUE TITLE
no output with rf_compare

### ISSUE THREAD

**Issue by Asperatus22** [dincarnato/RNAFramework#35]
Hi Danny
I did the git pull last week to use Shapeknot-smp, and it works fine.
but when i try to compare my structure with rf_compare i have the folowing screen output without any file output :

[+] Comparing structures to reference...

  Transcript    PPV     Sensitivity

  toto            0.79    0.80

[+] Comparison statistics:

  [*] Compared transcripts: 1
  [*] Excluded transcripts: 0 total
                            0 structure file parsing failed
                            0 mismatch between reference and query transcript sequences
                            0 missing structure file

[+] All done

have a great day

Lionel

**Comment by dincarnato** [comment]
Hi Lionel,

there should be no output. What output were you hoping for?
The only output that rf-compare will generate is an arc plot comparison of the two structures, and to activate it you need to specify the `-g` flag.

Best,
Danny

**Comment by Asperatus22** [comment]
Hi Danny,
it is the best way to look like a numb, ask a question to fast....
i was forget to use the -g option.
sorry, and thanks
Lionel
