### ISSUE TITLE
--only-mut issues

### ISSUE THREAD

**Issue by catherine-douds** [dincarnato/RNAFramework#40]
Hi Danny,

I am having trouble getting the -om mutations to work as expected. I am only getting reactivities at G when I run the following code:
rf-count -r -f file.fasta -m -la -ld -cc -mc 6 -q 30 -es -om G2T,G2C,A2N,T2N,C2N treated.bam untreated.bam

It seems like maybe it's only processing the first mutation? Do I have this formatted wrong?

**Comment by dincarnato** [comment]
Hi Catherine,

thanks a lot for reporting this! We made a change in the API and this slipped in between the cracks. It should be fixed now.
Please issue a git pull. The issue was only occurring with IUPAC codes.

Let me know!
All the best,
Danny

**Comment by catherine-douds** [comment]
It worked! Thank you!

**Comment by dincarnato** [comment]
Great Catherine, I'll close the issue then!
