### ISSUE TITLE
rf-count-genome: mutations by class

### ISSUE THREAD

**Issue by physnano** [dincarnato/RNAFramework#42]
Hi Danny,

I have a quick question regarding rf-count-genome. I noticed that rf-count has the capability to output mutation counts broken down by class via the --only-raw-counts option. Is there a similar functionality for rf-count-genome? Basically I would like to perform genome level counts with rf-count-genome and then be able to use rf-rctools extract/rf-rctools view to get all of the mutations within a particular region _broken down by class_. I am currently using --only-mut A2G,A2N,T2C,T2N within rf-count-genome but the output (example) is not broken down by class:

```
chr
ATGTGA
0,2,0,0,0,5
366,374,374,379,381,381
```

Where as I would be interested in the following:
```
chr
ATGTGA
T2C
0,2,0,0,0,0
A2G
0,0,0,0,0,5
...
...
366,374,374,379,381,381
```

Is this possible to achieve without running rf-count-genome with separate --only-mut options for each mutation class?

Best,

Will

**Comment by dincarnato** [comment]
Hi Will,

This is unfortunately not possible. Why don't you perform the analysis transcriptome level instead using rf-count and then set the -orc to get the mutations broken down by class?
Also, passing both A2G and A2N is pointless. A2N will "take over".

Best,
Danny

**Comment by physnano** [comment]
OK thanks Danny, I will try a few different things including the transcriptome level rf-count as suggested. Thank you again!

-Will
