### ISSUE TITLE
Question about RNAFramework rf-rctools view

### ISSUE THREAD

**Issue by MeganSylvia** [dincarnato/RNAFramework#46]
Hi Danny,

I was wondering if the rf-rctools view command was reversible. So we are able to view the rc file as a csv file. Can we then convert this csv file back to an rc file? This would allow me to test out some data filtering steps I would like to try.

Megan

**Comment by dincarnato** [comment]
Hi Megan,

it's not, but if you send me a sample file, I can write a script for you to enable to you do that.

Cheers,
Danny

**Comment by MeganSylvia** [comment]
Hi Danny!

I prefer the tab version of your rc-rftools view script, so I have attached an example output that looks like your rc-rftools view -t output!

Megan
[CW_filtered_tab.txt](https://github.com/dincarnato/RNAFramework/files/13032761/CW_filtered_tab.txt)

**Comment by dincarnato** [comment]
Here you are! Please let me know if it gives you issues.
You will have to either specify the path to the RNA Framework's `lib/` folder inside the script, or simply add it to your `$PERL5LIB` environment variable by:

```bash
export PERL5LIB=$PERL5LIB:/path/to/RNAFramework/lib
```

Cheers,
Danny

[txt2rc.gz](https://github.com/dincarnato/RNAFramework/files/13034309/txt2rc.gz)

**Comment by dincarnato** [comment]
Did it work?

**Comment by MeganSylvia** [comment]
Hi Danny!

Sorry for the delay! I didn't see your original email. I just tried running
it on the example one I sent you earlier and it worked perfectly! Thank you!

Megan
