### ISSUE TITLE
Shannon entropy

### ISSUE THREAD

**Issue by Asperatus22** [dincarnato/RNAFramework#47]
Hi Danny
I'm looking on the .wig file from the rf-fold/shannon output.
I notice that some of my nucleotide doesn't have any value.
I tried to figure out why but failed in my investigation.
Can you please help me to understand how this value is calculated? 
Best regard ,
Lionel Bigault

**Comment by dincarnato** [comment]
Hi Lionel,

as per WIG standard, if the Shannon is 0, then it is not reported, so most likely that's the reason.
You can find the details about how is Shannon entropy calculated here: [https://rnaframework-docs.readthedocs.io/en/latest/rf-fold/](https://rnaframework-docs.readthedocs.io/en/latest/rf-fold/)
Can you give me the sample XML file you are using the parameters of rf-fold so I can check?

Best,
Danny

**Comment by dincarnato** [comment]
Hi Lionel,

I can confirm that the regions with no Shannon entropy values are those with Shannon = 0.
If you load the wiggle track along with the dp file of the bp probs on IGV, you can immediately see that indeed these are the regions with extremely high base-pairing probability (see figure).

Hope this solves!
Best,
Danny

<img width="850" alt="image" src="https://github.com/dincarnato/RNAFramework/assets/194672/2631fdd1-a74c-49a9-9618-4594dabca7d3">
