### ISSUE TITLE
rf-count-genome outputs 0 % mutated alignments

### ISSUE THREAD

**Issue by mohamedbahru** [dincarnato/RNAFramework#49]
I have the Oxford nanopore sequencing data. 

I have done the alignment with splicing using Minimap2 aligner.

Then I used rf-count-genome function to calculate the mutations per base.

I got the 0 % mutated alignments. Why?

The output was displayed as follows.

[+] Making output directory...
[+] Guessing file types:

  [4m[1mSample[0m    [4m[1mType[0m    [4m[1m5'-end trimming[0m    [4m[1mLibrary type[0m

  sorted    BAM     Ignored            unstranded

[+] Importing chromosomes from reference, and building count table base structure...
[+] Inspecting SAM/BAM file headers...
[+] Sorting SAM/BAM files...

  [-] Sorting sample "sorted" (PID: 62495)

[+] Calculating per-base mutation counts and coverage. This may take a while...

  [-] Processing sample "sorted" (PID: 62622)

[+] Statistics:

  [*] Sample "sorted": 54 chromosomes covered - 0/7671926 (0.00%) mutated alignments

[+] Cleaning up temporary files...
[+] All done.

Could you please help me? Thanks.

**Comment by dincarnato** [comment]
Can you please paste below 2-3 representative lines from your BAM file?

**Comment by mohamedbahru** [comment]
[mohamedb@binf cDNA_no_UV_crosslink]$ samtools view sorted.bam | head -5
7183e3b4-9a78-440c-b1c2-4629c10c24d3    16      chr1    3053489 60      1444S48M2D2M1D17M2D17M1D17M1D6M1I4M1I4M1I19M4D10M2D3M1D10M1D6M5D9M1D1M1D19M1D25M1I5M1I2M1I4M2I2M1I6M1D6M1D13M1D24M3D3M1D4M2I8M1D3M1I43M1D2M1D12M1D11M1D8M1I9M1I7M2I2M1D4M3D12M1D9M1D6M3I9M3I5M4D2M1D28M2D2M1D5M1I12M1I8M5D10M1I11M1I9M1I14M2I33M1I13M1D17M1D4M1D4M3D18M1I4M2I4M1I22M1D7M1D7M1I4M4D7M1D4M1D7M1D5M2D19M1D27M1D2M1D1M1D5M3D24M1D6M1I10M2D4M3I23M1D15M1I13M3D22M1I64M2D10M1I2M1D7M1D14M1D5M3D21M1I4M1I4M1D19M1D25M1D6M2D10M1I10M1D10M1D19M2D2M1D2M2D8M1I12M1I4M1D11M2I4M2D10M2D2M2D18M1D10M1D20M1D11M1D13M13D47M3D15M1I56M1D7M1D4M2D30M1I6M2D22M1I11M34S *       0   0ACCAGCATTGGCTATCTCCATGTCAGGGGGATAGGACAGTAAGGCAAGAAAACACAATGAGGAGATATAGCTACACTGCAGCTTGGAAAGCGGAAATACACCCATCATCACAGAGCTTCCATAAGATGGTACATATACATATGGACAGATCAACCAAGTCACCTCATGCCAGGCACGTGTGTGGGTGTGTGTGTGTGTGTGTGTGTGTGTGTATTTAATGGTAATTTGAAAATCACATACACATATCGATAAAAATCGCATGGAAGACACTCATCATCACTCATAAGATTGGGAGAAACTGGAAACCATATTCTGCTGACTGGATTGGATGGGTATTTTCAAGGAAACATAGACATGTGGAAAGAGGAAAGAAATAGATGCTCATATTAGTGCTGTGAAAAAGAAATGGTACAACCACTGCAGAGACACAGTGTGGAAATTCTCAAAGATCTAGAAAACTGTTGCATAGACCCAGCCATTTCTTTACTAGCCATATATAGACATTGTTGGGTACACCTTGTTAATAATATATTGGGTTATAAGGAGCTAAAGACTACCATATCCTATGTATTCATGCATAGATAAAATTCTATAAATATAATAAATGATATAGATATGTGGAAAGATCATCATTCTCAAAAGACTGGATGTTGGTACTTAGATATAAATGGTTATGGTGACAAAACCACATAAAACTGAATACAATTTCATAAACAAATATATATAATTGGATCTTATACAAAGAAAATAATAACATAGATAGAAAATAAGAGCATAGAATAGGACACAAGAGTAGTATGGAAGAACAGAAGAGATATCTGTTGTTTCATAACCTACGGGTTCCATTTGAGGATGATAGGATGTTTGAGGAAGATAGAGACGGGCTGACAATACATCCCACACTTAAAACTGATCTACTATACACTGGGTGGTTGAGAAAATGCACAATCTTTCCTTGAAAAAGCTATAGCTGATTCCATTAGTGACCATCACAGAAACTGATTCTATAACAGTCCATCAAGAAAGACAAAAGATCTGTGGCACAAGTTCAGAAAGCAAGTCTCAGCCAAGGCCTAGTTGCAACATCTACACAATGGATGGTCACTGTAAGGAGACATCAGGCCACTGTGGCAGAGACAAGAGGCTGAATCTGCCTGGAGACCATACAGTAACAACAAGATGGGAACAAAGAGAGGAGATACAGGCTCCATTTTTCATTCCAATGCTGTTATTATCTCAAGGCAGGAACCATGAAAGCTCAGGAAAAGGAAGGGAATCTAGGAACACTGTCTCCACATAAGACATCTTACTGTTATTAAAACAGGGAAGGTAGAGGGCAAGGATACATAGTCAACAAATGACCTGGAGTTCTATAAATGGCTAGGACATGCCTTCCATGGCACGTGATCTGTCTTTACACTGTCCACTGTCACAGTTGGTTGGCAGCAGAGTGACAACCTAGACAGGGGACTGTGACATCAAAAGAGTGTTACAAAAACATGGTATCACCTAAAGCATGTCCTAGCCATTTCTGGAAAATGGAAGCAAGTTCCTTTCCACTCATGCATCCTTCCATCTCCTCTGCCTCCCAGACAGAATGCTGCCATGTGAACATGTTGTGTATCCCAATGTGTTTCCTGACCTACATGATACTGCCTTGAGCCTCACTACTGCAACATGCGCTGCATGAAAGTGAACCTGTATCCTATCTTTGTTCCTATCTCTGTTGTTATCTCTGGGTTTTCTAGGAGGAACTGAAGCCTTTCCCTGTCTCTGCCACATGATCACCTGATGTCCCACAAGAACCATGGACTGAATTGTTTAGTGTTGGAAACTGCCTCTTGGGAATCTAGGGCTCCTCTTTGCTAACTTTTATTGGAGAACTTCCTTGTCTGACCTACTACGTTAATTATACCAGAGTTCACTGTGATGAGTGAATGGGAATAGCTCATCTGCTTTTCAATAAAGTTAGCACCATTCTGATCCTACCCAGCTAGATAGTCAGTGGTAGTTAAGTGCTTATAATGTTGTCATTATCATTTCTTATCTATTTCTAGACATTCTCATCATCCTCAATGAATTTGTCTATGAAAGAACACACTCTGTCTCTTCCTGTTCTTCCATACTCTTGATATCTATTCATATTCTGATTTGTCTACATCCATTTCTATAATAAATCCAATCTGTGTACCTTCTAAATTATGGAAAATCTATACATTCTACTATTGTTCATAGCATAATATTGTAAGGTTCATCCTTTCTGAAAAATACGAATAACTTCATAGATCTTAAGAGATGATCAGATTTGACATATCTAACACCATTTATTATGATCAATTTATCTATACATGGTATGCATGGGCTGTGGTCATCTTTAAGTGACCATAATGAATGCTGTTATTAACAAGGTGTACGTATATGTTGAGGCTCTTGCTTTGATTATTCTGTGCATTGGCTAGAGTTATTGCCTAGTCACACTGGTAAACTTGAGTGTTTTAAAGTACCATGTGTCTTCTGCAGTGGCTATATCATTATTTAGCAGCACTGAAATCTGGCATTGATTTCTTTCTCTTTCACATGTATTATGTCTGAATTGCTATTCGAGAGAGATAGAAGACAGAGTCTTGTGGAGTTAGTTATACTTCCTACTGAGTGATCATGAGTACTTTTTATGAATTTCTGGACATCTGTATGAATTTTTGGAGAATTTCTATTTAAACACACACACACACACACACACACACACAGATCTATAGATTGAGGGAGGGATTAGGTGTTTGTGTTTATGTATTGATATATGTATATGTACATATTTATGAATCTTTGATAATAATGGGTTCTGTGAGGGTTCCAGAGCTTTCAGTGTTAGCTATCTCTCTCCTACACTGTCTTTAATCTTGCTGTCCTAATCCCTGACATTCATACAGATGCAACTGAACGAAGTAATAGGCAT    $$$%&('&$$$$$$%%&'+32222100/0/1+(('%%$$$'%&%%%$##%%&&%$%&&&'&&'&''&%$$$$$%%&%###$%%''%&%$$$%%&'(&&&&&''''&&%&$$%&))))&'&%$&&%%&&('(''&%%))'&%$$$%&(((((+(&%&''''../0/*''((+,./14<<>44445BCDQHHISFHKIIIKSKHE;;::964/)('&&('&'''*&'''(+'&$$%'&''(''''()))))(***('('(&%%&('&&&%%*+,411/.)('&&&&&''('&&&&('))()++,-,+'&&%()('&&%$$$%%%%''&'%%$%&&')(''&&'(('('&)+*++.0278.---/.,,,*./0*++)&&%%$$%&&'&&&(,,+''&'')*(&&%%'%$$######$$&')**'&%'%&(((%%)%%&$%%%%%&&%(''())))*&'&%$%$$$$)%%$%%&'(*..-)(('&%%$$%$$%%$$$$%%%%(*''&&%%%%%&''''$%%&''%%'&%%%%((*)''(''%$$%%$$$$$$'&%%'&'''''%%%%%$$$&''''&)%$$%%''*(**('((())())((''(((,,*)(((('*+,()*+--+,)&%%%&(%$$%$$%$%'&%%%%&&&*)(&&%$$##$%&%%%+'*)(((&&&(%$$$$'&$$$$$%%&'&(((&&&&%&%%%&'&&&+0'&&%%%$##$$&&&&((*****)*-'&&&&+--,0)'&&&%%&&%%%%$%%%%,0-)('&&&&'('(()'&%%%$$$$&'&''(***.--))((,,+('&&&)+,,,,,+++)(''&&(()))(('##$$%'(-(&&&%%%&'&&').--1*'''&&'&*,,****(&%%$$####$$$%%&%$$$%%&'('(&%&&&&%$$$&&%&&'/,,,,,(+,''''&&'&&'(()''&&%%%&',-('''.,,*(&&&&'**(((((+,-.*)&#$$$$))+//.,,-++)*+)''&%$%'(,*($$$%&''(('&'+-+*(*&%%$%&(('%$$$$$%%&***+(,*(&%&&$$$$&&(*+)((((((*((&&&&$$%%%$&%%%%$%%%%%%%$$'('%$''().024441/-+(&%$$&(,/.-,,**,..*)%$$#$$$%'())&&&&%%%$$'(.0-,,,(''&&*)))'*)'*)(+&&&&&)+(('+++***),'&')(*)'&&&&()*)&&%%$$%%%$$$$%&'('''&&'')&%%$$%&%%%'(++*)(%%%%%)(**)('(''(((*)(('&%&)+,,-,+()))(%$$$%%%%&&&'$$%(),,)(+)(('''&&%&&&&&(''&''&$$$$%%%&%%''''('&%$$$$$$%%&+'++(((//..//01667755..-,+''''&)&%%$$$%&&%&&,--...))))11000-%$$#%()%$%%&(&%&%&&&&++-/+**-.31-..)))*+122///-('''''/)&&&&-,0*(''&'%$$$%%'))))..(((('&&&&&--,+,,*))*+&))))*'&'&$#$#$$$$$%&')'(''&)''')('%%%'&('())((((((((&&%%$%&(),+)'%$#$$$&&$$'-*'&$$$$$$$$%%%&(*('&&''&()((**+.2-%%%%%0//*)))'&&&%%$$%%&((&$%&%$$$$$%'''()'&''&%%%))(''''+**)''&&%%%$$%%%%''&''-+***'&%%&))*++**&%$%%''''$$$%%%$%%&%&')&(,*+**+--0&%%&')&&''')((((/)%%&&&&&&''../(%$%&*+*+,(''(('(-)'&&%%$$%$$$$%&')(&&&%%%%%&**''&&&&'&&&%$$%&&'&'&%%&%'%%%&&('''(')%%%'',&&&&%$$%&&&(''&&&&$$'(*****...11241130//1**--.///0/+**+-2466631('(&&+*)'''**+,*))''&'%$$$$$''&%&&&()*/097540&&%%%&''),,+'$$$$%%-//0***&&&&%&'(()(&$%%&&'')('&%%'',(((&'&''&&&)*+'%''&''%'%&&''((&$%%$%&&&&$%%&&(%&&'%$$%'$$&&%&%%%&%&%%%%&&''&''('''')''&&'''&&%%&%%%&&%%%&*+****%$&%%'((($$%%(+,+))))(*&&&(('''(4471599888330/--,+)''&')*./,+*,,//.+++++(&&&&('%$%%%'')()(''''**++&&&&',,,.((*+(('(()&%&'+00///.,&%%%$%&&'(--10.+((*))*)'')(((%$%%$%%%'&(('()*,1100----*++++*&**)+**)))(''$%&&&&''&&'')-,--,.0014*))(()))+,,/876/-,,+++./.----))'&(*,-/-****+/*((+((%&&&%&('(''%%%''''&%%&%%%&$$$%%&%%%%%&%%%&''*++**)&%&''()))))(''()*,,.24472.0/..*&%&$$$%&&%&)&&')&''''''')&&'&%&&&'(+*+*+((.0/1//02/00-+*+.1/,--))012122.*))*,3&'%%&%&'''(()(''''(&(((''&%%%$%$$$$$$%&&%$$$%%%'&%$$$$$$#$$#$&'&%%&(((,--00/,,+,,0151.--,**)(&&&...-,2'(&&'()++&'()),,,,,,00358797878//--*)%$$%%%%%%(())(('%%'&%'(&%%&(1220,*%%%%%$%%&)(&&&&&30((**++,++(*)**/+**('''',,*()((&''''&++++((+++''''',)((&'&''1/-.,((**+00,,+()**(('&&&'''*'')-/,%&%%&&&(('''()(&&&(('''''(*)*)*)+****&'&&&'&&&$$$$%&$$$$####$$$#    NM:i:353        ms:i:541        AS:i:504        nn:i:0  ts:A:+  tp:A:P  cm:i:41 s1:i:269        s2:i:0  de:f:0.1834  SA:Z:chr1,3053555,+,1553S1381M114D19S,60,419;   rl:i:99
7183e3b4-9a78-440c-b1c2-4629c10c24d3    2048    chr1    3053555 60      1553H23M1D5M2D6M1I7M1D4M1D15M2I3M1D13M1D3M1D11M2I4M2D8M3D6M1I16M1D10M1I2M1D9M1I12M3D1M1D8M1I1M1I4M1I19M2I4M1D15M1D13M3D14M1D2M1D10M3D13M2D16M1I14M6D7M1D2M1I10M1I8M2D9M5D5M1D10M1D10M1I15M1I8M1D12M3D15M1D7M1I3M1D6M1I14M3D4M1D3M2I22M4I5M2D8M1D1M1D6M2I6M1I1M2D11M2D11M1D21M1D5M1I40M1I3M1I19M1I9M1D8M1I17M1D3M1I12M2D5M3D4M1D13M1I13M1D6M4D5M1I4M1D2M5D3M2D2M6D7M2D2M3D3M2I2M1D9M1I42M1I3M1I35M1D9M1I5M1I5M1D33M25D25M1D7M1D5M5I2M1D3M1I7M1I6M2I9M1D21M1I7M1D7M1D6M1I7M1D14M1I7M1D8M1I17M4D1M1D6M2I13M2D7M4D9M3I2M1D19M1D9M2I25M4D12M2D32M17D1M1D24M1I16M2D13M1I3M1D30M1D1M1D11M2D3M1D7M1D11M1D3M1D12M1I16M2I9M19H      *       0       0       CCATGGAAGGCATGTCCTAGCCATTTATAGAACTCCAGGTCATTTGTTGACTATGTATCCTTGCCCTCTACCTTCCCTGTTTTAATAACAGTAAGATGTCTTATGTGGAGACAGTGTTCCTAGATTCCCTTCCTTTTCCTGAGCTTTCATGGTTCCTGCCTTGAGATAATAACAGCATTGGAATGAAAAATGGAGCCTGTATCTCCTCTCTTTGTTCCCATCTTGTTGTTACTGTATGGTCTCCAGGCAGATTCAGCCTCTTGTCTCTGCCACAGTGGCCTGATGTCTCCTTACAGTGACCATCCATTGTGTAGATGTTGCAACTAGGCCTTGGCTGAGACTTGCTTTCTGAACTTGTGCCACAGATCTTTTGTCTTTCTTGATGGACTGTTATAGAATCAGTTTCTGTGATGGTCACTAATGGAATCAGCTATAGCTTTTTCAAGGAAAGATTGTGCATTTTCTCAACCACCCAGTGTATAGTAGATCAGTTTTAAGTGTGGGATGTATTGTCAGCCCGTCTCTATCTTCCTCAAACATCCTATCATCCTCAAATGGAACCCGTAGGTTATGAAACAACAGATATCTCTTCTGTTCTTCCATACTACTCTTGTGTCCTATTCTATGCTCTTATTTTCTATCTATGTTATTATTTTCTTTGTATAAGATCCAATTATATATATTTGTTTATGAAATTGTATTCAGTTTTATGTGGTTTTGTCACCATAACCATTTATATCTAAGTACCAACATCCAGTCTTTTGAGAATGATGATCTTTCCACATATCTATATCATTTATTATATTTATAGAATTTTATCTATGCATGAATACATAGGATATGGTAGTCTTTAGCTCCTTATAACCCAATATATTATTAACAAGGTGTACCCAACAATGTCTATATATGGCTAGTAAAGAAATGGCTGGGTCTATGCAACAGTTTTCTAGATCTTTGAGAATTTCCACACTGTGTCTCTGCAGTGGTTGTACCATTTCTTTTTCACAGCACTAATATGAGCATCTATTTCTTTCCTCTTTCCACATGTCTATGTTTCCTTGAAAATACCCATCCAATCCAGTCAGCAGAATATGGTTTCCAGTTTCTCCCAATCTTATGAGTGATGATGAGTGTCTTCCATGCGATTTTTATCGATATGTGTATGTGATTTTCAAATTACCATTAAATACACACACACACACACACACACACACACCCACACACGTGCCTGGCATGAGGTGACTTGGTTGATCTGTCCATATGTATATGTACCATCTTATGGAAGCTCTGTGATGATGGGTGTATTTCCGCTTTCCAAGCTGCAGTGTAGCTATATCTCCTCATTGTGTTTTCTTGCCTTACTGTCCTATCCCCCTGACAT       ''+,-..55776610//..//(((++'+&%%$$$$$$%&'(''''%%&%%%$$$$&''&''(&&&&&%&&'''(()+(),,)(%$$'&&&%%%%$$$%()))(+,-,,+)&%&'(()*(((''('()**()%%%%%()*++('%%%&%$$%%&)''&&'''('&%$$$$%%%$$%%&&)*)(&&&&')*()'&',)***+++'((+)&&&&&+()*')*')))*&&''(,,,-0.('$$%%%&&&&))('%$$$#$$%)*..,**,,-./,(&$$%&(+-/144420.)(''$%'('$$%%%%%%%$%%%%&$%%%$$&&&&((*(((((()+*(&&$$$$&&%&(*,(+***&%%$$$$$%'((&%$%%&*(*+-+'&'((''&%$$$(*,('%$%&'')+*)++-,,.//+))$$$$#&)*.-,+(((((**'&&&&(*,,.'''(-,'&%%%&&'')(('&&'&&'''',+(,,,,,/'&&%&&$$$%&&&&%&('('&%%$$$%&%%$$$####$$%%&(****,,*&'&&'''*1--.)'&&'&%%%&&&(-('%$$##'(()))((&&''()+++,,,,,+)&&&'(+,,(())--.***(''&'&$$$$%%%&')(('('&&&&'()-0,%%%%$%%%%&&%%&&&')0,--+&&&&'-*)*****((&&&&$$##$%%%&&'0+&&&'&%%%&%&&&&(((&'&%%$$$$$&'$$$$%(&&&((()*'+%%%&%$##$$%&&()*&&&%%%%&'%$%$$%$$%(&%%%&),+--+*)(,+*'(((()*,,(((''(())())((('(**(*''%%$$%)&''''&$$$%%%%%'''''&'%%&'$$$$$$%%$$%''('')*((%%%%&'%%''&%%$''''&%%%%%&&''*(%%%%$$$$%%$$%$$%%&'(()-..*('&%%$%%)$$$$%$%&'&*))))(''(%&&%%%%%$&%%)%%(((&%'%&'**)'&$$######$$%'%%&&(*)''&''+,,(&&&'&&%$$%%&&)++*0/.*,,,./---.8720.++*+)&'('(('&&''()'&&%$%%'&''%%%%$$$%&&'()(%&&'+,-,++)())'(&&&&'(''&&&&&'()./114,+*%%&&&'(&%%&('('(***()))))(''''(''&'%$$&'+('''&*'''&'(&&'()/469::;;EHKSKIIIKHFSIHHQDCB54444><<41/.,+((''*/0/..''''&%&(+(((((&%$$$%&'))%%&''('(&&%%&&$%&'&))))&%$$&%&&''''&&&&&('&%%$$$%&%''%%$###%&%%$$$$$%&''&'&&'&&&%$%&&%%##$%%%&%'$$$%%'((+1/0/00122223       NM:i:419    ms:i:367 AS:i:293        nn:i:0  ts:A:+  tp:A:P  cm:i:10 s1:i:110        s2:i:0  de:f:0.2076     SA:Z:chr1,3053489,-,1444S1475M86D34S,60,353;    rl:i:99
1f6d3106-86b3-410a-9e47-236ad099f307    2048    chr1    3055661 37      48H6M598I167587N3M1D1M1D10M1D6M1D7M2D26M1I12M1D5M1D13M5D11M2D2M2D8M1D3M2D5M2I9M1I19M2D10M2D9M1D21M1D7M1I3M1D8M1D15M1D10M1D62M3I6M1D12M1D9M2I9M2D16M4I4M1D3M1I3M1I17M1I23M4D33M2D5M1D32M1I10M1I2M1I14M1D9M2I3M3D1M1D22M31H       *       0       0   CTATCTTTCTTTTTTTTTTTTGCCTTTTAAGAGTAAACTAAGATTTTACGATACCTAAACTGATTGATGACTTTTCATTGACAAAACATAAATACTGCATTCTGAAGGGGCAGTCACTAATTGCACTTTTGATCAAATTTGTAAGAACAGTCTGACTGAAGACTACAAAGATTATTAGAGAGTGGCATGTGCATGATTTATTAATTTTCAAGAAATACATCAGCATTGTAATTTAGAATTGATAGTCTGTGAGAGATGAACAATTAAGCAATTTACAAGTTCGGAGTATGACGTGGTCTGATACAGATTAAGGTTTTGATTCTTGAGCATTTTTAAAAACCTTCCCCATCTACAGCACACAGACATACATCTGTGCTCAAACCAGGGAAGACTGTCTCTAACTTCACCCACAGGAAGCTAGTTTTGGGCCCAGCATTGGGCAACAGATGGCTGGGAGGAATGAGGAGAATGACTTTTCAGATGATGTTTTTTTTTTTGGCAAAAAATGTTTTCGGCACAACAATTTTAATTACAATTGGATGACAATTATGAGAGCTTTGTTTTCAGAGACTTTGTGGTAAAGCAAAAAACTCTCCAAAAAAATAAACTTTATAATTGTATTAATCATAATAAAATCGGTTGTGCCCAAAACAATTCTTTTCGCGAAAAAAAAACGTGTTGTAAAGTCGCTCATCCTCCGCATGGTTGGCCATGCTCCACCAACTAGCTTTCTGCTGAGCAGAGTCTTGACACAGTTTCCTGTTCCACACAAATAATCTGATTTTGTGTGTGGATGGTGTTTGAAATATGAACAATCAAACCTGAGTTGTATTTGATGCTCAATGCCATATCTATGAGCTCGCAATTGCTAAAAATATTCATCCCTCAGATACTGTAATTATCAATTTACAATTGTTGTGCATATTTTTCTGGTTCAAGTAAATAGATTTTTGTGGCACTGTCGGCTTCTTAATAACTTTGCAACCCCTTCTAGTTACAACTGCTCCTAAAAATGAATTAAAATGTGATTAGTCACTTCCCTTACACCAAGTGTTTGAAATGTTTTGTCAACTAGTTATTTAATTCAAAGAGTTTGGTATTGTAAAATTTAAAACTAGTTATTTAAAAGGCAAAAAAAAAAGAA        ,,*(')'&%%((),03446<=21/../-)(''))%%%&*%%$%%%%0,.(''%%''&(('(&&%)(((((((((*(''('(---.0///*)))(((&%%%%$#$&''(*((&&&$$$$$&&'())))+,+&&'&%&&$%&#####%%$$&+&&%%&&%&(')&&%%&&'()**'&&%%&&&&)((())*.))((&''&'()&$%%%&%$%&%%&&&(((('('&&&*))&%%&-'&&&'().1*('''',+++/.12((''&))))))*()))'&''(&&(%%&&(('''+*''%%&$%%%%%%(&&''(&%%%((+*,&&%''$$&'())+))),,+++**&$$$'(-+++++.-.1/--(''&&'(()''(('**-,(&%&%&+)&'(&%&&)('&&&&%&&&&(*-(+32+''(+,(''(()(),,01.+*(((&&()((*('&&%&'145545<50(&((''&%('&&&''*/)*(''&())*.//3456;CE1100333756,,,++'%%%%))*,,-11,2/.++'&%$$$$%%''''&%$$$%&%%&''')*&'''/%$$%&))*())/(''%%(&&'')+,,&%%$#$$%&)*+,,)('%&&'&*%%%$$$$%&))*,('&%$$%))*)&&'''(&''&%&&'&&()*)*124'&&%&()/-(&&%&%(%$$%%***)+***+,++*)))+'%%%%&()&')*.3-*(&''''%'&&*,.--,(/,)('&%$%%&'&&'(%&&&)*,,,+)*()+,)))+))()(&&&&%%%$$%'&&'((&&%'&&&%$$$%&%&''&%$$$$'((+&&%&*+.)''&&%$%&&+%&0....-.//06.-,,)(&&&((**)&&%%&'&&'(()))+(('&%'$%%')/.-+'&&&(&&'(''%%%%&,((-,,,**,****)+*,,,-2)'&%&&%&%$$$%%&&'&&&)((%%%&'(&&%%%%%$%&&'&&&&+'&&&('&&%$$%%&'&&&'(,**++,0,,+((('(,/47(''')))0/.*'%$$%')*)))))&'''*'',(((&''&*+*)*)((*,.-.*)%%%$&%%%%%&,+'),,*)))%(%%&-''((*001110112-&')('*'%$$$%&*&(-,+01///.,,-,(&&&*    NM:i:725        ms:i:201        AS:i:125        nn:i:0  ts:A:+  tp:A:P  cm:i:13 s1:i:95 s2:i:0  de:f:0.181      SA:Z:chr5,89354138,-,31S547M28D645S,1,114;      rl:i:45

**Comment by dincarnato** [comment]
Your reads miss the MD tag.
Please run "samtools calmd" to add it, and rerun rf-count on the resulting BAM file.

Danny
