### ISSUE TITLE
rf count 'mutation' and mutated reads?

### ISSUE THREAD

**Issue by qianxu05172019** [dincarnato/RNAFramework#5]
Hi,

I am counting the mutations in my DMS treated and untreated bam files.  The output  of rf-count looks like:
[*] Sample “unTreated": 50587 transcripts covered [A: 21.24; C: 25.20; G: 26.64; T: 26.92] - 11595/102122 (11.35%) mutated reads
[*] Sample “treated": 57468 transcripts covered [A: 52.87; C: 32.83; G: 9.35; T: 4.96] - 86127/112904 (76.28%) mutated reads

I am very worried because even the untreated sample has 11.35% mutated reads. I wanted to ask:

1. How does RNA Framework define "mutation"? For example, this position needs to be covered 10 times to be taken into account. And this position should be mutated at least 5 times out of 10 times, then this position is confirmed as "mutated".

2. How does RNA Framework define "mutated reads"? Is 11.35% mutation rate normal for an untreated sample?

Thanks for developing this tool!

**Comment by dincarnato** [comment]
Hi Qian,

the results you got are actually great for a DMS-MaPseq experiment.
11.35% of mutated reads vs. 76.28% is really outstanding. Also the mutation frequencies clearly show that the DMS treatment worked very well. Any mutation (indel/mismatch) with respect to the reference sequence is counted and even reads with a single mutation are counted as "mutated reads". Any cell line/organism/sample will have some natural variation with respect to the reference sequence used, as well as you have random errors introduced during the sequencing and during the library prep as well. But even if you would have seen 25% mutated reads in untreated sample I would have considered this as a great experiment. Your results are very good. The experiment went definitely fine.

Hope this helps.
Best,

Danny
