### ISSUE TITLE
rf-map&rf-count

### ISSUE THREAD

**Issue by Shuang1248** [dincarnato/RNAFramework#52]
Hi Danny,

       I am using RNA framework to analyze  my SHAPE-seq data, but I got the similar error when I used rf-map and rf-count like this:
       Can't use an undefined value as an ARRAY reference at RNAFramework-master/rf-map line 444.
       Can't use an undefined value as an ARRAY reference at RNAFramework-master/rf-count line 619.
       These have been bothering me for a long time，could you please help me?

Thanks

**Comment by dincarnato** [comment]
Hi,

To understand what is going on I need the files you are working with (or a small case example to reproduce the issue) + the exact command line you are executing.
Also, can you run rf-map with the -kl option and share the logs/ folder in the output?

Danny

**Comment by Shuang1248** [comment]
Hi Danny,
  This is the exact command line I am  executing: rf-map -b2 -p 20 -o rf_map -ca3 AGATCGGAAGAGC -cl 18 -ctn -b5 3 -bi /data/RNAframework/transcriptome/transcriptome_sorted -bnr SRR933552.fastq.gz -kl
   This is the log file: [SRR933552_cutadapt.log](https://github.com/dincarnato/RNAFramework/files/13837227/SRR933552_cutadapt.log)
    And I sent the other files to the email dincarnato@rnaframework.com.

Thanks for your help!

**Comment by Shuang1248** [comment]
Hi Dannny,
     I am not sure why you can not receive my email,  to solve this problem about rf_map, I try to trim adapters by cutadapt and map reads by bowtie2 and sort by samtools instead of using rf_map, and then I use rf_count to calculate the RT stops, can I analyze by this way? 
     However, when I use rf_count, I also got an error: Can't use an undefined value as an ARRAY reference at RNAFramework-master/rf-count line 619.  And this  is my exact command line: rf-count -p 4 -o rf_count -f ../transcriptome/transcriptome.sorted.fa -ndd --sorted Map.sorted.bam
     Because you can not receive my email, so I attach some pictures of files I used.
![bam](https://github.com/dincarnato/RNAFramework/assets/155648139/392a593c-477a-4ace-8236-a5b45071eb24)
![transcriptomefa](https://github.com/dincarnato/RNAFramework/assets/155648139/8e1a4dbd-ff8c-4fb7-9c6f-60ec4c11e853)


Thanks

**Comment by Shuang1248** [comment]
Hi Dannny,
     I am not sure why you can not receive my email,  to solve this problem about rf_map, I try to trim adapters by cutadapt and map reads by bowtie2 and sort by samtools instead of using rf_map, and then I use rf_count to calculate the RT stops, can I analyze by this way? 
     However, when I use rf_count, I also got an error: Can't use an undefined value as an ARRAY reference at RNAFramework-master/rf-count line 619.  And this  is my exact command line: rf-count -p 4 -o rf_count -f ../transcriptome/transcriptome.sorted.fa -ndd --sorted Map.sorted.bam
     Because you can not receive my email, so I attach some pictures of files I used.
![bam](https://github.com/dincarnato/RNAFramework/assets/155648139/fbf07f3b-babe-42bf-9d5e-ddb9595ee27e)
![transcriptomefa](https://github.com/dincarnato/RNAFramework/assets/155648139/8015c2da-e53e-4906-b631-a5fd470ce373)



Thanks

**Comment by dincarnato** [comment]
Sorry Shuang but I cannot reproduce the issue. I am gonna need the files. Please upload them somewhere (drive, wetransfer, etc.).

**Comment by Shuang1248** [comment]
Hi Danny,
      I upload data on wetransfer, this is the link:    https://we.tl/t-rg47Mfy9jY    , I hope this link will work.
      My command line: rf-count -r -f ~/transcriptome/transcriptome.sorted.fa Map.sorted.bam
      The information of error:  Can't use an undefined value as an ARRAY reference at RNAFramework-master/rf-count line 619.

Thanks!

**Comment by dincarnato** [comment]
Hi Shuang,

sorry but it looks there is an issue with your RNAFramework installation.
The files get processed smoothly on my system.

```
$ rf-count -r -f transcriptome.sorted.fa Map.sorted.bam

[+] Making output directory...
[+] Guessing file types:

  Sample        Type    5'-end trimming

  Map.sorted    BAM     0 nt

[+] Getting transcripts from reference, and building count table base structure...
[+] Inspecting SAM/BAM file headers...
[+] Assuming that provided SAM/BAM files are already sorted. Skipping sorting...
[+] Calculating per-base RT-stops and coverage. This may take a while...

  [-] Processing sample "Map.sorted" (PID: 2757)
```

Please delete your local install and re-clone the RNAFramework from this repository.
Also make sure you have a recent version of Perl installed on your system (5.22 or greater).

Best, 
Danny

**Comment by Shuang1248** [comment]
Hi Danny,
      I can get these outputs as well ,but after " [-] Processing sample "Map.sorted" (PID: 2757)", it will inform me of  the error: Can't use an undefined value as an ARRAY reference at RNAFramework-master/rf-count line 619.
      If you didn't get the error, I think it may because there is an issue with my RNAFramework installation.

Thanks

**Comment by dincarnato** [comment]
Ok, then let me finish running the analysis and see if I get the error as well.
This is why I asked for the FULL OUTPUT.

**Comment by dincarnato** [comment]
It just finished running smoothly:

```
[+] Statistics:

  [*] Sample "Map.sorted": 16553 transcripts covered [A: 22.81; C: 30.32; G: 18.66; T: 28.21]

[+] Cleaning up temporary files...
[+] All done.
```

Please make sure you have the latest version of the RNA Framework (`git pull`) and a recent version of SAMTools.

**Comment by Shuang1248** [comment]
Hi, Danny:
       Thank you very much, I  updated the samtools, and I can run smoothly successfully!

**Comment by dincarnato** [comment]
Great!
Best,
Danny
