### ISSUE TITLE
rf-correlate

### ISSUE THREAD

**Issue by Shuang1248** [dincarnato/RNAFramework#53]
Hi Danny,
      I use rf-correlate to  calculate the correlations of experiments using XML files, but I do not know what the results mean. Does the second column represents the correlation, and the third column represents the variance? And can I get the relations between replicates as a whole instead of single transcript?
![f75865483e2f5b902abefb22cc2a951](https://github.com/dincarnato/RNAFramework/assets/155648139/ef21654f-6f70-4798-a61b-8bc88f7a469d)

**Comment by dincarnato** [comment]
Hi Shuang,

you are right, I forgot to mention this in the manual.
The second columns is the correlation, the third column is the p-value.
If you want the correlation as a whole, you can find it in the console output.

Best,
Danny

**Comment by Shuang1248** [comment]
Oh， Danny， I see it, thank you for your help!
