### ISSUE TITLE
Permission denied for group

### ISSUE THREAD

**Issue by Asperatus22** [dincarnato/RNAFramework#54]
Hi Danny,  
I tried to work on filed generated by a script run by an other user and i can't due to pemission issue.  
It may be due to the mode of creation in perl script, for exemple line 268 in rf-map, "mode => 0755"   
Could  you consider changing to 0775 ?
One more time, many thanks for your work
Lionel

**Comment by dincarnato** [comment]
Hi Lionel,

0755 is the right set of permissions. Not everybody want all users from the group to be able to access their folder.

I'm sorry, but this won't be changed.

Cheers,
Danny
