### ISSUE TITLE
rf-count "File contains unsupported line endings ("\r")"

### ISSUE THREAD

**Issue by jsromanowski** [dincarnato/RNAFramework#55]
Hello,

I am currently trying to use the rf-count command to analyze SNP and indel data from a sorted .bam DNA file (I am assuming this program works for both RNA and DNA files). I downloaded RNAFramework and brough the directory to PATH. 

I then ran the following command:

**$ rf-count -f NHEJAssayDshortref.fas -orc -m D2_NHEJ_FLsorted.bam** 

Here, NHEJAssayDshortref.fas is my reference file and D2_NHEJ_FLsorted.bam is my input .bam file I would like analyzed. 

I received the following output:

**[+] Making output directory...
[+] Guessing file types:

  Sample              Type    5'-end trimming

  D2_NHEJ_FLsorted    BAM     Ignored

[+] Getting transcripts from reference, and building count table base structure...
[!] Exception [Data::IO::Sequence->new()]:
    File contains unsupported line endings ("\r")
    -> Caught at /mnt/c/users/josep/Downloads/RNAFramework/lib/Core/Base.pm line 126.**

I am not entirely sure what the unsupported line ending error message is referring to. Is this error because I am using a DNA .bam input rather than RNA .bam? Any help is appreciated. Thanks

**Comment by dincarnato** [comment]
Hi,

The issue relates to your FASTA file, which was most likely generated using a Windows text editor.
You should make sure your file has only "\n" line endings. This can be done on Linux via the **dos2unix** program.

Best,
Danny
