### ISSUE TITLE
rc file to mm file

### ISSUE THREAD

**Issue by Asperatus22** [dincarnato/RNAFramework#59]
Hi Danny,
I merged replicate to better cover some transcript with succes.
I would try draco on this experiment but while rf-map generate a .mm file, rf-rctools merge does not.
Is there a way to convert rc file to mm?
One more time thanks for you work.
Lionel

**Comment by dincarnato** [comment]
Hi Lionel,

Unfortunately you cannot go from RC to MM. The MM stores every single read, while the RC only stores transcript-level counts.
In future releases I will add MM manipulation to rf-rctools, but for the moment my suggestion is to merge the BAM files and reprocess the merged file with rf-count to get a new MM file.

If that's too time consuming, let me know and I'll see if I can get you a simple script to merge two MM files.

Cheers,
Danny

**Comment by Asperatus22** [comment]
Hi Danny,
As rf-count is one of the most time consuming job, i think a script to merge two MM files will be the best option.
Thanks a lot
Lionel

**Comment by dincarnato** [comment]
Hi Lionel,

the latest RNA Framework is not online.
While merging of MM files is not possible yet, the new rf-count has multithread support (on a transcript basis, meaning that multiple transcripts are processed on separate threads) which should significantly speed up runtimes.
Would you mind give it a shot and let me know?
Also, the issue in rf-eval has been solved.

Cheers,
Danny

**Comment by Asperatus22** [comment]
Hi Danny
Thanks for these release
i ll wrote a python script for merging mm file
Best
Lionel

**Comment by dincarnato** [comment]
Hi Lionel,

I would like to flag that during the last update a bug was inadvertently introduced (2 lines commented out during tests and not uncommented before commit), which caused mis-calling of deletions in rf-count.
I apologize for this if it caused any inconvenience and advise you to pull the latest commit asap.

Moreover, we found out that on some systems the multithreading was having issues, causing, with files containing large numbers of transcripts (which I believe is your case), the number of running threads to decrease over time, down to just 1. This is now solved and, if you give it a shot, you should now observe a massive speed up in rf-count.

Cheers,
Danny

**Comment by dincarnato** [comment]
Hi Lionel,

the new version of RNA Framework with the new `rf-mmtools` module you requested is now out.
Please `git pull` and enjoy!

Cheers,
Danny
