### ISSUE TITLE
rf-fold error: Environment variable DATAPATH is not set

### ISSUE THREAD

**Issue by laure-g** [dincarnato/RNAFramework#64]
Dear Danny,

I'm following commands from the application case "SHAPE_Map". I could run step 1 to 7, and obtained the folder named "HIV_norm/" , containing a single XML file. But I run into an issue with rf-fold (step 8).

$ rf-fold -m 2 -g -md 500 -w -pk -km 2 -ko 100 -pw 1600 -po 375 -wt 300 -fw 3000 -fo 300 HIV_norm/

[+] Checking method's requirements...

  [!] Error: Environment variable DATAPATH is not set

Sorry if it is basic, but I don't know how to solve this issue or set the DATAPATH here. So any help would be very appreciated!

Best,

Laure

**Comment by dincarnato** [comment]
Dear Laure,

the `$DATAPATH` environment variable is something that is required by RNAstructure.
Do you have RNAstructure installed on your system? If yes, you need to locate the `data_tables/` folder located within your RNAstructure install dir, then set the `$DATAPATH` variable as it follows:

```bash
export DATAPATH=/path/to/RNAstructure/data_tables/
```

Alternatively, you can change the command line to:

```bash
rf-fold -g -md 500 -w -pk -ko 100 -pw 1600 -po 375 -wt 300 -fw 3000 -fo 300 HIV_norm
```

to use the ViennaRNA package instead.
Hope this helps!

Best,
Danny

**Comment by laure-g** [comment]
Dear Danny,

It worked, thank you! I had to modify the export function because export only works in bash shells. In tcsh shells:
/setenv DATAPATH /path/to/RNAstructure/data_tables/

Then, the issue was solved. Many thanks!

Laure
