### ISSUE TITLE
rf-fold -  1 folding failed

### ISSUE THREAD

**Issue by laure-g** [dincarnato/RNAFramework#65]
Dear Danny, 

I am running the SHAPE-Map Application Case. All steps work until rf-fold, I get

```
[myfolder]$ rf-fold -m 2 -g -md 500 -w -pk -km 2 -ko 100 -pw 1600 -po 375 -wt 300 -fw 3000 -fo 300 HIV_norm/ --ow

[+] Checking method's requirements...
[+] Making output directory tree...
[+] Importing XML file(s) [1 imported]
[+] Folding RNA structures [Last: none]
[+] Folding statistics:

  [*] Folded transcripts:    0
  [*] Discarded transcripts: 1 total
                             0 XML parsing failed
                             0 constraint file generation failed
                             0 FASTA file generation failed
                             **1 folding failed**
                             0 I/O error
                             0 pseudoknotted folding failed

[+] All done.
```

Our IT told me even though the RNA.pm file is present (path = /usr/local/share/perl5/5.32/), it seems the script cannot find it. Is there a way to fix this issue please? 

I checked closed issues as well but it did not help us to fix the issue.

Best wishes,

Laure

**Comment by dincarnato** [comment]
Dear Laure,

i don't think that's the issue. If the program wouldn't be able to find RNA.pm, it would say so, and it is not (judging from the output you pasted above).

There must be some other issue. Can you please re-run the program by appending the `-KT` parameter? This will cause the temporary `tmp/` dir inside your output folder to be kept.

Can you please zip that folder and share it with me?

Best,
Danny

**Comment by laure-g** [comment]
Dear Danny,

Thank you for the reply. Please find attached the tmp.zip file.


Best wishes,


Laure


________________________________
De : Danny Incarnato ***@***.***>
Envoyé : lundi 15 juillet 2024 14:55:25
À : dincarnato/RNAFramework
Cc : Laure Gauthé; Author
Objet : Re: [dincarnato/RNAFramework] rf-fold - 1 folding failed (Issue #65)


Dear Laure,

i don't think that's the issue. If the program wouldn't be able to find RNA.pm, it would say so, and it is not (judging from the output you pasted above).

There must be some other issue. Can you please re-run the program by appending the -KT parameter? This will cause the temporary tmp/ dir inside your output folder to be kept.

Can you please zip that folder and share it with me?

Best,
Danny

**Comment by dincarnato** [comment]
I do not see any attachment. Can you mail it to me?

**Comment by laure-g** [comment]
Dear Danny,



Please find attached the tmp.zip file. (2nd attempt)



Best wishes,



Laure


De : Laure Gauthé ***@***.***>
Date : lundi 15 juillet 2024 à 3:20 PM
À : dincarnato/RNAFramework ***@***.***>, dincarnato/RNAFramework ***@***.***>
Cc : Author ***@***.***>
Objet : RE: [dincarnato/RNAFramework] rf-fold - 1 folding failed (Issue #65)


Dear Danny,

Thank you for the reply. Please find attached the tmp.zip file.



Best wishes,



Laure



________________________________
De : Danny Incarnato ***@***.***>
Envoyé : lundi 15 juillet 2024 14:55:25
À : dincarnato/RNAFramework
Cc : Laure Gauthé; Author
Objet : Re: [dincarnato/RNAFramework] rf-fold - 1 folding failed (Issue #65)


Dear Laure,

i don't think that's the issue. If the program wouldn't be able to find RNA.pm, it would say so, and it is not (judging from the output you pasted above).

There must be some other issue. Can you please re-run the program by appending the -KT parameter? This will cause the temporary tmp/ dir inside your output folder to be kept.

Can you please zip that folder and share it with me?

Best,
Danny

**Comment by dincarnato** [comment]
@laure-g no attachment that I can see. Please mail it to me.

**Comment by laure-g** [comment]
Dear Danny,

I sent it again to ***@***.******@***.***>.

Best wishes, Laure

De : Danny Incarnato ***@***.***>
Répondre à : dincarnato/RNAFramework ***@***.***>
Date : lundi 15 juillet 2024 à 4:29 PM
À : dincarnato/RNAFramework ***@***.***>
Cc : Laure Gauthé ***@***.***>, Mention ***@***.***>
Objet : Re: [dincarnato/RNAFramework] rf-fold - 1 folding failed (Issue #65)


@laure-g<https://github.com/laure-g> no attachment that I can see. Please mail it to me.

**Comment by dincarnato** [comment]
Ok, maybe we can jump on a call and look into this together if you want

**Comment by dincarnato** [comment]
Let me know if you want to try and get this fixed.

**Comment by laure-g** [comment]
Dear Danny,

I transmitted all the info to our IT and wait for his feedback! I’ll come back to you asap.

Best wishes
Laure

De : Danny Incarnato ***@***.***>
Répondre à : dincarnato/RNAFramework ***@***.***>
Date : mardi 16 juillet 2024 à 1:26 PM
À : dincarnato/RNAFramework ***@***.***>
Cc : Laure Gauthé ***@***.***>, Mention ***@***.***>
Objet : Re: [dincarnato/RNAFramework] rf-fold - 1 folding failed (Issue #65)


Let me know if you want to try and get this fixed.

**Comment by dincarnato** [comment]
I think it would be helpful if we could trace the error. It would definitely make the IT life easier.

**Comment by laure-g** [comment]
Then, we could schedule a call tomorrow before 5 PM or Thursday if you have time?

De : Danny Incarnato ***@***.***>
Répondre à : dincarnato/RNAFramework ***@***.***>
Date : mardi 16 juillet 2024 à 2:22 PM
À : dincarnato/RNAFramework ***@***.***>
Cc : Laure Gauthé ***@***.***>, Mention ***@***.***>
Objet : Re: [dincarnato/RNAFramework] rf-fold - 1 folding failed (Issue #65)


I think it would be helpful if we could trace the error. It would definitely make the IT life easier.

**Comment by dincarnato** [comment]
Closing the issue cause it's solved
