### ISSUE TITLE
Issu in rf-eval

### ISSUE THREAD

**Issue by Asperatus22** [dincarnato/RNAFramework#66]
Hi Danny
I think there is an issue in rf-eval line 157. 
While testing if reactory are from directory or file you test for $structs instead of $reacts
    die "\n\n  [!] Error: Provided file lacks .xml extension\n\n" if ($structs !~ m/\.xml$/);
Best regards and thanks for your works
Lionel

**Comment by dincarnato** [comment]
Hi Lionel,

yes, thanks, it's already fixed in the upcoming release.
We are finalizing the multi-thread version of rf-count. Will release it soon.

Cheers,
Danny

**Comment by Asperatus22** [comment]
i guess you are aware that if you change $structs to $reacts, the xml is imported but there is still an issue with filename for the test with structure id.
i'll wait for the next release and use directory instead
Best regards 
Lionel
