### ISSUE TITLE
Config::Simple Module Not Found when runing rf-norm in Docker container

### ISSUE THREAD

**Issue by maxtrp** [dincarnato/RNAFramework#68]
I am experiencing an issue where the Perl module Config::Simple cannot be located when I try to run rf-norm. The error message is:

"""
Can't locate Config/Simple.pm in @INC (you may need to install the Config::Simple module) (@INC contains: /home/ubuntu/rnaframework/lib /home/ubuntu/conda/lib/perl5/5.32/site_perl /home/ubuntu/conda/lib/perl5/site_perl /home/ubuntu/conda/lib/perl5/5.32/vendor_perl /home/ubuntu/conda/lib/perl5/vendor_perl /home/ubuntu/conda/lib/perl5/5.32/core_perl /home/ubuntu/conda/lib/perl5/core_perl .) at /home/ubuntu/rnaframework/lib/RF/Config.pm line 4.
BEGIN failed--compilation aborted at /home/ubuntu/rnaframework/lib/RF/Config.pm line 4.
Compilation failed in require at /home/ubuntu/rnaframework/rf-norm line 34.
BEGIN failed--compilation aborted at /home/ubuntu/rnaframework/rf-norm line 34.
"""

Despite me not being familiar with perl and its packages, I think the problem is due to the Perl interpreter being run within the Conda environment. However, Config::Simple is currently installed outside the Conda environment in the Dockerfile. As a result, the @INC paths do not include the location where Config::Simple was originally installed.

I have managed to get around this by installing the perl packages within the conda environment by adding them to the mamba command (in the Dockerfile):

"""
Setup Bioconda channel configuration and install dependencies
RUN conda config --add channels defaults && \
    conda config --add channels bioconda && \
    mamba install -y \
        python=3.10 \
        gxx_linux-64 \
        bowtie>=1.2.3 \
        bowtie2>=2.3.5 \
        samtools>=1.2 \
        bedtools>=2.0 \
        cutadapt>=2.1 \
        viennarna>=2.4.0 \
        rnastructure>=5.6 \
        perl-xml-libxml \
        perl-config-simple && \
    mamba clean -a -y
"""

However, I am aware this is a quick fix and you may want to implement a more permanent solution in future versions.

Best,
Max

**Comment by dincarnato** [comment]
@kenibrewer can you take a look at this? Tnx.

**Comment by dincarnato** [comment]
We have now dropped the Config::Simple, therefore it won't be an issue anymore! Cheers, Danny
