### ISSUE TITLE
Issues installing XML::LibXML dependancy

### ISSUE THREAD

**Issue by nickforino** [dincarnato/RNAFramework#7]
Hi Danny,

Very much looking forward to making use of your software! 
Unfortunately I've been unable to install the XML::LibXML module. After doing some reading I believe this may be a more common issue for other users, so I wanted to bring this to your attention. I've also opened up a support thread here: [https://github.com/shlomif/perl-XML-LibXML/issues/61]
If you have any advice for workarounds, I'd greatly appreciate it.

Best,
Nick

**Comment by dincarnato** [comment]
Hi Nick,

I am currently working to a pure-Perl replacement that will make RNA Framework able to read XML files without the need for the XMLlib. That said, if I am not mistaken, the only program relying on XMLlib is rf-index. You can avoid using it and build the reference index for bowtie/bowtie2 yourself.

I will notify you as soon as I will have the XML reader ready.
Hope this helps!

Best,
Danny

**Comment by nickforino** [comment]
Hi Danny,

Thanks so much for your reply. In fact, I perform my indexing and alignments manually anyway, so I won't be relying on rf-index. This is great news!

Cheers,
Nick
