### ISSUE TITLE
missing MD tag

### ISSUE THREAD

**Issue by xuebingwu** [dincarnato/RNAFramework#70]
When running rf-count using bam files generated by rf-map, we got the following error:

Error: Missing MD tag, run 'samtools calmd' to fix

So we did the following to fix this:

samtools calmd -bAr $file $indexFolder/hg38_ncbiRefSeqSelect.fa > $file.md.bam

however, we still got the same error with the new bam file. Any suggestion? This is using RNAFramework v2.8.9 on ubuntu 20.04 on a x86_64 machine.

**Comment by dincarnato** [comment]
Hi @xuebingwu,

can you please share a chunk of this BAM file, along with the command line you are running?

Thanks.

Danny

**Comment by dincarnato** [comment]
And also the reference Fasta please.

**Comment by xuebingwu** [comment]
The reference is standard hg38, too large to upload
[test2.bam.zip](https://github.com/user-attachments/files/17181092/test2.bam.zip) (unzip first)

command and output 
----------------------------
rf-count -r -m -ow -f $indexFolder/hg38_ncbiRefSeqSelect.fa test2.bam 

[+] Making output directory...
[+] Checking files:

  Sample    File format    Sorted    Indexed    5'-end trimming

  test2     BAM            Yes       Yes        Ignored

[+] Getting transcripts from reference, and building count table base structure...
[+] Inspecting SAM/BAM file headers...

  [!] Warning: Only 19080/19236 reference transcripts are present in sample "test2" header.
               All transcripts absent in reference will be skipped.

[+] Copying RC base structure...
[+] Queuing jobs...
[+] Calculating per-base mutation counts and coverage. This may take a while...

|████                                              | (Done: 7.50%)  Error: Missing MD tag, run 'samtools calmd' to fix

[+] Statistics:

  [!] Processing failed for sample "test2" (Error: Missing MD tag, run 'samtools calmd' to fix)

[+] Cleaning up temporary files...
[+] All done.

**Comment by dincarnato** [comment]
Sorry but reference is not hg38. The reference is ncbiRefSeqSelect, extracted from hg38. That file should not big if zipped, and it's needed for me to replicate the issue.

**Comment by dincarnato** [comment]
If the file is too big after compression, just upload it to some service like WeTransfer.

**Comment by xuebingwu** [comment]
the reference was generated using rf-index:

rf-index -b2 -pb 4

[Uploading hg38_ncbiRefSeqSelect.fa.zip…]()

**Comment by xuebingwu** [comment]
the reference was generated using rf-index:

rf-index -b2 -pb 4
[hg38_ncbiRefSeqSelect.fa.zip](https://github.com/user-attachments/files/17181309/hg38_ncbiRefSeqSelect.fa.zip)

**Comment by dincarnato** [comment]
Hi Xuebing,

thanks for reporting this. The issue was with transcript names with non-alphanumeric characters.
It is solved now. Please issue a `git pull` and let me know if it works!

Cheers,
Danny

**Comment by xuebingwu** [comment]
it's working now! thanks for your prompt response!

**Comment by dincarnato** [comment]
Thank you for reporting and helping us improving RNA Framework!
