### ISSUE TITLE
rf-correlate for positions below coverage threshold

### ISSUE THREAD

**Issue by xuebingwu** [dincarnato/RNAFramework#71]
Hi Danny,

When I used rf-correlate to calculate the correlation of DMS mutation ratio between two samples, some transcripts got negative correlations. When looking at the mutation ratio in genome browser (wiggle files), it appears these transcripts tend to have low coverage (-nan 100 in rf-norm), such that most positions have only sufficient coverage (non NaN ratio) in one but not both samples. This would lead to a negative correlation if rf-correlate treat NaN as 0. Is this the case? If so, can you add an option to ignore positions that are NaN in either sample, i.e., only use positions with sufficient coverage in both samples?

the commandline I used:

rf-norm -t rf_count/treated.rc -u rf_count/untreated.rc \
            -i rf_count/untreated.rc.rci,rf_count/treated.rc.rci \
            -o rf_norm/sample1 \
            --scoring-method 1 --norm-method 2 -rb AC --nan 100 

rf-correlate --ratio --min-coverage 100 --min-values 100 --cap-react 1 --keep-bases AC rf_norm/sample1 rf_norm/sample2

**Comment by dincarnato** [comment]
Hi Xuebing,

Can you send me 2 files you are comparing that give you negative correlation so that I can tell you what is rf-correlate doing?

Best,
Danny

**Comment by xuebingwu** [comment]
here are the two XML files

[Archive 2.zip](https://github.com/user-attachments/files/17204427/Archive.2.zip)

**Comment by dincarnato** [comment]
Hi Xuebing,

thanks. So, first of all, let me explain that all those parameters have no effect in this context:

`--ratio --min-coverage 100 --min-values 100 --cap-react 1 --keep-bases AC`

First of all, as explained in the docs, `--ratio --min-coverage 100` only have effect with input RC files. XML files already contain normalized reactivities, therefore there is no information in those files anymore about coverage nor raw counts. The `--ratio` instructs the program to calculate the ratio between raw counts and coverage in an RC file, before calculating the correlation.

The parameters `--cap-react 1 --keep-bases AC` also have no effect in your specific case, as you performed 90% Winsorization (which ranges between 0 and 1, therefore your reactivities are already capped at 1) on A/C bases (therefore you already only have reactivity data for A/C bases, while all the others are NaNs).

Therefore, the program is calculating the correlation on all the A/C bases for which a reactivity value is available in your dataset. `rf-correlate` only uses the values that are non-NaN in both samples, therefore NaNs are not treated as 0s.

In the two files you provided the non-NaN values are respectively:

```
0.461,0.675,0.752,0.000,0.317,0.291,0.582,0.816,0.291,0.000,0.000,0.922,1.000,0.401,0.000,0.922,0.752,1.000,0.922,0.752,0.317,0.872,0.752,0.752,0.966,0.582,0.291,0.675,0.582,0.675,0.966,0.000,0.000,0.000,0.000,0.752,1.000,0.582,0.070,0.000,0.000,0.000,0.000,0.401,0.070,0.000,0.000,0.047,0.291,0.816,0.401,0.922,0.872,0.461,0.361,0.872,0.000,0.000,0.000,0.000,0.675,0.922,0.752,0.000,0.461,0.922,0.582,0.000,0.966,0.211,0.000,0.816,0.752,0.000,0.582,0.471,0.147,0.582,0.582,0.752,0.816,0.816,0.000,0.461,0.675,0.291,0.461,0.211,0.147,0.000,0.582,0.752,0.872,1.000,0.000,0.000,1.000,0.147,0.816,0.211,0.872,0.007,0.007,0.582,0.675,0.816,0.752,0.000,0.000,0.000,0.675,1.000,0.461,0.752,0.461,0.461,1.000,0.147,0.291,0.461,0.675,0.752,0.582,0.872,0.582,0.401,0.291,0.752,0.291,0.872,0.922,0.582,0.675,0.461

and

0.671,0.578,0.578,0.812,0.114,0.000,0.000,0.179,0.000,0.289,0.671,0.671,0.747,0.916,0.000,0.038,0.458,0.000,0.000,0.458,1.000,0.179,0.458,0.812,0.114,0.179,0.000,0.328,0.284,0.000,0.179,0.671,0.458,0.000,0.289,0.812,0.458,0.867,0.000,0.867,0.671,0.114,1.000,0.234,0.000,0.812,0.867,0.000,0.812,0.671,1.000,1.000,0.038,0.000,0.000,0.234,0.578,0.000,0.000,0.038,0.000,0.578,0.000,0.867,0.000,0.458,0.000,0.000,0.179,0.000,0.000,0.179,0.867,0.812,0.000,0.867,0.038,0.000,0.747,0.960,0.179,0.747,0.458,0.114,0.038,0.747,0.000,0.867,1.000,0.000,0.114,0.179,0.179,0.267,0.289,0.747,0.671,0.458,0.000,0.747,0.812,0.960,0.812,0.812,0.578,0.812,0.916,0.578,0.289,0.578,0.000,0.000,0.458,0.000,0.747,0.289,1.000,0.916,0.578,0.289,0.114,0.000,0.179,0.114,0.812,0.284,0.960,0.578,1.000,0.747,0.578,0.114,0.867,0.671
```

If you input these values in any program (like R), you will see that correlation is indeed the same as reported by rf-correlate.

Hope this explains.

Cheers,
Danny

**Comment by dincarnato** [comment]
You can also try to take the full set of reactivities, NaNs included, put them into 2 R arrays, then run:

`cor.test(a,b,use="complete.obs")`

it will give you the same result.

**Comment by xuebingwu** [comment]
Hi Danny,

Thanks for looking into this!

**Comment by dincarnato** [comment]
No worries!
