### ISSUE TITLE
rf-mmtools issues

### ISSUE THREAD

**Issue by Asperatus22** [dincarnato/RNAFramework#72]
Hi Danny,

Still, me :)

i have some problem with rf-mmtools view, 
The script needs the index file as [target].mm.mmi despite that the one generated by rf-count is [target].mmi (same for merge)
rf-mmtools merge produce a .mm.mmi file. 
The script print id of the transcript and the sequence but not the mutations.

rf-mmtools merge create a .mm file with id and sequence but without any reads.

rf-mmtools stats does not print stats from my .mm file

i did not test the other command.

Best regards

Lionel

**Comment by dincarnato** [comment]
Also, all tools look for a `.mm.mmi`, as indicated in the docs.

**Comment by Asperatus22** [comment]
I obviously tried to merge old data. (2.8.2)
Once re indexed, i can view, stats, and merge.

one more time thanks a lot for your help

**Comment by dincarnato** [comment]
Great!
