### ISSUE TITLE
Issues rf-fold failed 

### ISSUE THREAD

**Issue by jinqiongli** [dincarnato/RNAFramework#8]
Hi Danny,

I am very appreciate for using RNAFramework, it helped me a lot !
Unfortunately I've been unable to use the rf-fold to fold RNA. 
the code is:
 ~/RNAFramework/rf-fold /home/jql/RNAFramework/201123/norm -t 25 -i -sh -o /home/jql/RNAFramework/201123/vienna
Here is my problem:
[+] Checking method's requirements...
[+] Making output directory tree...
[+] Importing XML file(s) [7 imported]
[+] Folding RNA structures [Last: none]
[+] Folding statistics:

  [*] Folded transcripts:    0
  [*] Discarded transcripts: 7 total
                             2 XML parsing failed
                             0 constraint file generation failed
                             0 FASTA file generation failed
                             5 folding failed
                             0 I/O error

[+] All done.
Because I failed to fold,  the output is the empty folder. I don't know how to solve this issue, so I wish I could get help from you.
Any suggestion will help me a lot.

Best,
Qiongli Jin

**Comment by dincarnato** [comment]
Dear Qiongli,

to reproduce the error I would need the XML files you are using.
Can you please share those (also by email if you prefer)?

Have the XML files been generated by rf-norm?

Best,
Danny

**Comment by jinqiongli** [comment]
Dear Danny，

Thank you for replying. Here is my XML files that I am using for rf-fold.

The XML files have been generated by rf-norm.

Best,
Qiongli Jin


发送自 Windows 10 版邮件应用

发件人: Danny Incarnato
发送时间: 2020年11月23日 23:58
收件人: dincarnato/RNAFramework
抄送: jinqiongli; Author
主题: Re: [dincarnato/RNAFramework] Issues rf-fold failed (#8)

Dear Qiongli,
to reproduce the error I would need the XML files you are using.
Can you please share those (also by email if you prefer)?
Have the XML files been generated by rf-norm?
Best,
Danny

**Comment by dincarnato** [comment]
Dear Qiongli,

here where? I do not see any file.

Danny

**Comment by jinqiongli** [comment]
Hi Danny,

Sorry, I send the rar file, which may the reason why you can’t see it.
Here is one of the samples:
<?xml version="1.0" encoding="UTF-8"?>
<data combined="FALSE" maxmutrate="0.2" norm="2-8%" offset="50" reactive="ACGT" remap="0" scoring="Zubradt" tool="rf-norm" win="50">
	<transcript id="R2" length="433">
		<sequence>
			CCAAACAAACAGAATCAGGTGACAGATAATGAGGATGTGATGAGGGTCTCTCCAAGATGT
			GGACCCAAGTGGCCATTGAATGGGCTCGATGGCTATCTGACTGATGTTTGGCAAAGCTAA
			AATTAAATCGTTTTTGCCTTTTCACGGGGAACAGAACATTGTTGTGAACAGCATATCAAA
			GCTTGCCCCAGCGCTTGTAGCTAGACTTTAGTTGTACAGTACCCCAAACACGGCAGCGAC
			GATTCCGTGTTAATGGGATGATCTTTAGGTTTCAGAAGGCAGCACAAGCAAATTTGCACT
			GATGTACTCTTTGTCAGGTGGTTTGACTTCTTGCTTTCTTTGTTGTTAGGGACTGGATAG
			CATGGATTAGGAATTTGATTATGATGAACTAATTCAAGAAATTGCCATAATCTTTGGTAC
			CTTGTGCGCCTGG
		</sequence>
		<reactivity>
			NaN,NaN,0.002,0.003,0.017,0.296,0.035,0.013,0.346,0.158,0.096,0.118,0.007,0.120,0.051,0.121,0.088,0.020,0.186,0.022,0.027,0.013,0.006,0.097,0.069,0.874,0.020,0.334,0.005,0.011,0.273,0.603,0.008,0.004,1.009,0.014,0.006,0.011,0.008,0.053,0.012,0.006,1.684,0.160,0.004,0.113,0.015,0.017,0.010,1.168,0.139,2.216,0.560,0.023,2.069,0.005,0.125,0.007,0.160,0.146,
			0.009,0.007,0.008,0.130,0.014,0.010,0.183,0.073,0.020,0.008,0.007,0.012,0.010,0.011,0.581,0.013,0.019,0.029,0.015,0.362,0.009,0.007,0.010,0.064,0.193,0.011,0.115,0.013,0.319,0.007,0.009,0.019,0.012,0.013,0.014,0.018,0.429,0.210,0.014,0.325,0.113,0.011,0.006,0.311,0.001,0.002,0.004,0.010,0.019,0.009,0.128,0.012,0.025,0.317,0.443,0.035,0.648,0.021,0.437,0.107,
			0.004,0.371,0.003,0.130,0.133,0.008,0.391,0.034,1.184,0.465,0.004,0.006,0.016,0.013,0.084,0.006,1.179,0.525,0.046,0.011,0.008,0.288,1.350,0.017,0.021,0.009,0.015,0.006,0.013,0.380,0.096,1.456,0.974,0.003,0.379,0.209,0.005,0.281,0.004,0.016,0.010,0.008,0.014,0.052,0.005,0.004,0.411,0.787,0.080,0.181,0.011,0.419,0.827,0.007,0.004,0.019,0.417,0.789,0.290,0.623,
			0.060,0.158,0.022,0.110,0.012,0.101,0.087,0.095,0.237,0.622,0.002,0.210,0.026,0.287,0.016,0.028,0.008,0.010,0.287,0.122,0.200,0.014,0.799,0.003,0.951,0.863,0.018,0.027,0.021,0.114,0.003,0.007,0.012,0.463,0.009,0.084,0.413,0.699,0.017,0.016,0.222,0.133,0.006,0.009,0.008,0.012,0.463,0.688,0.010,0.017,0.006,0.038,0.020,0.988,0.281,0.004,0.231,0.014,0.145,0.273,
			0.006,0.227,0.020,0.020,0.006,0.019,0.011,0.037,0.012,0.020,0.011,0.316,0.520,0.010,0.036,0.005,0.007,1.168,0.005,0.009,0.009,0.006,0.276,0.011,0.013,0.013,0.007,0.089,0.002,0.007,0.007,0.013,1.326,0.161,0.009,0.007,0.456,0.087,0.006,0.018,0.003,0.012,0.913,0.006,0.564,0.008,0.363,0.009,0.007,0.009,0.584,0.771,0.005,0.010,0.015,0.007,0.010,0.386,0.002,0.007,
			0.005,0.007,0.008,0.016,0.008,0.010,1.288,0.009,1.115,0.007,0.012,0.098,0.007,0.005,0.053,0.075,0.135,0.004,0.005,0.013,0.003,0.014,0.406,0.020,0.007,0.279,0.001,0.006,0.007,2.375,0.014,0.008,0.071,0.147,0.016,0.012,0.005,0.903,0.013,0.009,0.014,0.020,0.003,0.008,0.003,0.008,0.014,0.288,0.003,0.010,0.005,0.007,0.359,0.034,0.018,0.046,0.004,0.008,0.408,0.017,
			0.760,0.217,0.169,0.011,0.011,0.009,0.004,0.015,0.011,0.025,0.012,0.199,0.187,0.010,0.014,0.063,0.017,0.844,0.004,0.012,0.712,0.012,0.056,0.279,0.016,0.010,0.066,0.007,0.217,0.014,0.013,0.329,0.005,0.028,2.947,0.193,1.198,0.005,0.737,0.008,0.243,0.011,0.053,0.808,0.122,0.081,0.015,0.077,0.004,0.043,0.031,0.132,0.015,0.014,0.501,0.047,0.504,0.184,0.258,0.027,
			0.476,0.032,0.433,0.284,0.157,0.173,0.102,0.123,0.037,0.241,0.063,NaN,NaN
		</reactivity>
	</transcript>
</data>

I directed copy and paste it, could you get it right now?

Wishes,
Qiongli
发送自 Windows 10 版邮件应用

发件人: Danny Incarnato
发送时间: 2020年11月24日 17:25
收件人: dincarnato/RNAFramework
抄送: jinqiongli; Author
主题: Re: [dincarnato/RNAFramework] Issues rf-fold failed (#8)

Dear Qiongli,
here where? I do not see any file.
Danny

**Comment by dincarnato** [comment]
Dear Qiongli,

I am sorry but I have tried to use your file with rf-fold and your same parameters "-t 25 -i -sh" and if worked smoothly for me.
Can you share the actual XML file? Maybe there is some kind of issue with line-endings or similar?

Danny

PS. The use of the "-i" parameter instruct rf-fold to ignore the reactivities, so to predict the unconstrained structure.

**Comment by jinqiongli** [comment]
Dear Danny，
I want to predict the structure in vitro and ignore the reactivity, so I set  -i parameter.
I don't know how to show the file on git, so I directly send the xml files to your email, does this OK? 
Any advise that I can share my xml file to you?

Qiongli

**Comment by dincarnato** [comment]
Sure, just mail me the files: dincarnato@rnaframework.com

**Comment by jinqiongli** [comment]
Danny,
I guess maybe my rf-fold project have some problem when I installed it. Do you have any test.xml file that I can use to test my rf-fold is OK or not?
Qiongli

**Comment by dincarnato** [comment]
The files you sent me work as well. I do not really understand what kind of problem rf-fold can have. 
Is there a way I can get remote ssh access to your machine where RNA Framework is installed and try to solve the issue?

**Comment by jinqiongli** [comment]
Thank you, But I don't know how to remote ssh access to your server, it may take me some time to solve this. your work let me check my RNAFramework and I find that I didn't install RNAStructure (Because I don't intend to use it). I will install RNAStructure first and test whether I can use rf-fold or not. If this isn't worked, I will contact you again.

**Comment by dincarnato** [comment]
Dear Qiongli,

No need to install it, that's not the reason.
The program is complaining on XML parsing, and on folding.
Can you please try to execute "RNAfold -h" and show me the output?

**Comment by jinqiongli** [comment]
RNAfold 2.3.3

Calculate minimum free energy secondary structures and partition function of
RNAs

Usage: RNAfold [OPTIONS]...

The program reads RNA sequences, calculates their minimum free energy (mfe)
structure and prints the mfe structure in bracket notation and its free energy.
If not specified differently using commandline arguments, input is accepted
from stdin, and output printed to stdout. If the -p option was given it also
computes the partition function (pf) and base pairing probability matrix, and
prints the free energy of the thermodynamic ensemble, the frequency of the mfe
structure in the ensemble, and the ensemble diversity to stdout.

It also produces PostScript files with plots of the resulting secondary
structure graph and a "dot plot" of the base pairing matrix.
The dot plot shows a matrix of squares with area proportional to the pairing
probability in the upper right half, and one square for each pair in the
minimum free energy structure in the lower left half. For each pair i-j with
probability p>10E-6 there is a line of the form

i  j  sqrt(p)  ubox

in the PostScript file, so that the pair probabilities can be easily extracted.

Sequences may be provided in a simple text format where each sequence occupies
a single line. Output files are named "rna.ps" and "dot.ps". Existing files
of the same name will be overwritten.
It is also possible to provide sequence data in FASTA format. In this case, the
first word (max. 42 char) of the FASTA header will be used for output file
names. PostScript files "name_ss.ps" and "name_dp.ps" are produced for the
structure and dot plot, respectively.
Once FASTA input was provided all following sequences must be in FASTA format
too.
The program will continue to read new sequences until a line consisting of the
single character @ or an end of file condition is encountered.



  -h, --help                    Print help and exit
      --detailed-help           Print help, including all details and hidden
                                  options, and exit
      --full-help               Print help, including hidden options, and exit
  -V, --version                 Print version and exit

General Options:
  Command line options which alter the general behavior of this program


  -v, --verbose                 Be verbose.

                                    (default=off)
  -i, --infile=<filename>       Read a file instead of reading from stdin

  -o, --outfile=<filename>      Print output to file instead of stdout

      --noPS                    Do not produce postscript drawing of the mfe
                                  structure.

                                    (default=off)
      --noconv                  Do not automatically substitute nucleotide
                                  "T" with "U"

                                    (default=off)
      --auto-id                 Automatically generate an ID for each sequence.
                                    (default=off)
      --id-prefix=prefix        Prefix for automatically generated IDs (as used
                                  in output file names)

                                    (default=`sequence')

Structure Constraints:
  Command line options to interact with the structure constraints feature of
  this program


      --maxBPspan=INT           Set the maximum base pair span

                                    (default=`-1')
  -C, --constraint[=<filename>] Calculate structures subject to constraints.
                                    (default=`')
      --batch                   Use constraints for multiple sequences.
                                    (default=off)
      --canonicalBPonly         Remove non-canonical base pairs from the
                                  structure constraint

                                    (default=off)
      --enforceConstraint       Enforce base pairs given by round brackets ( )
                                  in structure constraint

                                    (default=off)
      --shape=<filename>        Use SHAPE reactivity data to guide structure
                                  predictions


      --shapeMethod=[D/Z/W] + [optional parameters]
                                Select method to incorporate SHAPE reactivity
                                  data.
                                    (default=`D')
      --shapeConversion=M/C/S/L/O  + [optional parameters]
                                Select method to convert SHAPE reactivities to
                                  pairing probabilities.
                                    (default=`O')

Algorithms:
  Select additional algorithms which should be included in the calculations.
  The Minimum free energy (MFE) and a structure representative are calculated
  in any case.


  -p, --partfunc[=INT]          Calculate the partition function and base
                                  pairing probability matrix.
                                    (default=`1')
      --MEA[=gamma]             Calculate an MEA (maximum expected accuracy)
                                  structure, where the expected accuracy is
                                  computed from the pair probabilities: each
                                  base pair (i,j) gets a score 2*gamma*p_ij and
                                  the score of an unpaired base is given by the
                                  probability of not forming a pair.
                                    (default=`1.')
  -c, --circ                    Assume a circular (instead of linear) RNA
                                  molecule.

                                    (default=off)
  -g, --gquad                   Incoorporate G-Quadruplex formation into the
                                  structure prediction algorithm.

                                    (default=off)

Model Details:
  -T, --temp=DOUBLE             Rescale energy parameters to a temperature of
                                  temp C. Default is 37C.


  -4, --noTetra                 Do not include special tabulated stabilizing
                                  energies for tri-, tetra- and hexaloop
                                  hairpins.
                                    (default=off)
  -d, --dangles=INT             How to treat "dangling end" energies for
                                  bases adjacent to helices in free ends and
                                  multi-loops
                                    (default=`2')
      --noLP                    Produce structures without lonely pairs
                                  (helices of length 1).
                                    (default=off)
      --noGU                    Do not allow GU pairs

                                    (default=off)
      --noClosingGU             Do not allow GU pairs at the end of helices

                                    (default=off)
  -P, --paramFile=paramfile     Read energy parameters from paramfile, instead
                                  of using the default parameter set.


If in doubt our program is right, nature is at fault.
Comments should be sent to rna@tbi.univie.ac.at.

**Comment by dincarnato** [comment]
Ok, let's try to find out the problem. The program says that 2 files failed XML parsing, and 5 files failed folding. Can you please send all of the 7 files?

**Comment by dincarnato** [comment]
There is an undocumented parameter in rf-fold, the “-KT” parameter.
Can you please re-execute rf-fold with that parameter added?
This will make rf-fold leave the “tmp/“ folder in your output folder. I will need to look to the content of the tmp folder. Please compress it and send it to me.

Danny

**Comment by jinqiongli** [comment]
wait me for a little second

**Comment by dincarnato** [comment]
I think the issue might be caused by your ViennaRNA version.
Can you please try installing the latest version?

**Comment by jinqiongli** [comment]
conda list viennarna
# packages in environment at /home/jql/.conda/envs/RNAFramework:
#
# Name                    Version                   Build  Channel
viennarna                 2.3.3                hfc679d8_2    bioconda
conda update viennarna
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.
conda list viennarna
# packages in environment at /home/jql/.conda/envs/RNAFramework:
#
# Name                    Version                   Build  Channel
viennarna                 2.3.3                hfc679d8_2    bioconda

**Comment by dincarnato** [comment]
This is not the latest version.
You should install it manually from the package.
You need ViennaRNA v2.4.11 or greater.

**Comment by jinqiongli** [comment]
I install it from packages ViennaRNA v2.4.16, but I don't know how to let RNAFramework use the latest version not the conda viennarna, could you teach me?
![image](https://user-images.githubusercontent.com/58067017/100095281-33438580-2e95-11eb-8cf8-b347e3a31336.png)

**Comment by dincarnato** [comment]
What's the full path to the ViennaRNA 2.4.16?

**Comment by jinqiongli** [comment]
/home/jql/ViennaRNA-2.4.16

**Comment by dincarnato** [comment]
Are the executables in that folder? Does /home/jql/ViennaRNA-2.4.16/RNAfold exist?

**Comment by jinqiongli** [comment]
There is no RNAfold exist in folder directly, but in viennaRNA-2.4.16/test/ there is one RNAfold
![image](https://user-images.githubusercontent.com/58067017/100096152-9681e780-2e96-11eb-9990-2830fbe609ab.png)
![image](https://user-images.githubusercontent.com/58067017/100096191-a699c700-2e96-11eb-96a9-274fe3c1f925.png)

**Comment by dincarnato** [comment]
did you compile it? or did you just downloaded the package? check the manual, you should issue the "./configure", then "make" and "make install".

**Comment by jinqiongli** [comment]
Dear Danny,
Really appreciate you, thank you for spending so much time for solving my problem. I am desperate for 3 days , because I  am a green hand in data analysis, no one could help me and I am stucking in my problems, this is the first time I asking for help on Internet. I think we could close the issue, Thank you again!
Best wishes,
Qiongli Jin
![image](https://user-images.githubusercontent.com/58067017/100101994-f0d27680-2e9d-11eb-9510-3cbaf71c547e.png)

**Comment by dincarnato** [comment]
Great to hear it worked!
Best,

Danny
