### ISSUE TITLE
rf-fold tries to run ViennaRNA regardless of specified folding method

### ISSUE THREAD

**Issue by nickforino** [dincarnato/RNAFramework#9]
Hello Danny, 

I hope you had a relaxing holiday season!

I'm running into some odd behavior of the rf-fold tool, in that it attempts to run the ViennaRNA package irrespective of the folding method I request.

`rf-fold -m 2 -p 4 -g sample_region.xml` returns the following:
`[!] Error: ViennaRNA package's Perl module RNA.pm is required.
             Please ensure that ViennaRNA package v2.2.0 (or greater) is installed and try again`

Any help would greatly appreciated, thank you Danny!

Best,
Nick

**Comment by dincarnato** [comment]
Hi Nick,

independently of the folding method used, the ViennaRNA perl bindings are required for certain steps (e.g. to calculate the energy of the structure). You should install the ViennaRNA package with Perl bindings and run the program again.

Hope this helps!
Danny

**Comment by dincarnato** [comment]
Hi Nick,

Can I close the issue?
Thanks,

Danny

**Comment by nickforino** [comment]
Hi Danny,

Thanks for your response!

Feel free to close the issue, but I should add some more context to my
issue in particular:
Unfortunately, I've been unable to get ViennaRNA installed on my system
(mac OS 10.16.6) due to a general incompatibility between newer mac OSs and
certain perl modules that are dependencies of ViennaRNA. It seems that the
newer mac OSs meddle with some perl installations in ways that are above
me, despite my asking around the community and my attempts to fix them for
a couple weeks now. I understand that RNAFramework should make use of the
most up to date versions of the RNA folding algorithms, but I'd just like
to notify you that there are roadblocks to getting ViennaRNA installed on
some mac systems until the Perl community can rectify the issue.

Again, thanks for your help, and looking forward to making further use of
RNAFramework,
Nick

**Comment by dincarnato** [comment]
Hi Nick,

I do not think the OS is the issue.
I work on MacOS 10.15.7 and I have the latest ViennaRNA package installed, with Perl bindings.

Maybe, the easiest solution for you would be to setup a Linux virtual machine, and install RNAFramework there?

Best,
Danny

**Comment by nickforino** [comment]
Hi Danny,

I'll give that a try, thank you for the advice and answering my questions.
Feel free to close the github issue.

Best,
Nick

**Comment by dincarnato** [comment]
Hi Nick,

Ok. I suggest you to try installing ViennaRNA using MacPorts.

Best,
Danny

**Comment by coffeebond** [comment]
> Hello Danny,
> 
> I hope you had a relaxing holiday season!
> 
> I'm running into some odd behavior of the rf-fold tool, in that it attempts to run the ViennaRNA package irrespective of the folding method I request.
> 
> `rf-fold -m 2 -p 4 -g sample_region.xml` returns the following: `[!] Error: ViennaRNA package's Perl module RNA.pm is required. Please ensure that ViennaRNA package v2.2.0 (or greater) is installed and try again`
> 
> Any help would greatly appreciated, thank you Danny!
> 
> Best, Nick

I have the same problem. I do have ViennaRNA and I see the RNA.pm file. Do you know why I still get the same error like this? Do I have to tell rc-fold where to find RNA.pm file?

Thanks!

**Comment by coffeebond** [comment]
> Hi Nick,
> 
> I do not think the OS is the issue. I work on MacOS 10.15.7 and I have the latest ViennaRNA package installed, with Perl bindings.
> 
> Maybe, the easiest solution for you would be to setup a Linux virtual machine, and install RNAFramework there?
> 
> Best, Danny

Can I ask what do you mean by “Perl
Bindings”?

**Comment by dincarnato** [comment]
Hello coffeebond,

this is a closed issue, you should have opened a new one.
Anyway, it looks like you did not install the Perl bindings for Vienna.
When you compile ViennaRNA from source, you should make sure that the Perl bindings are being installed as well. Also, in case you have multiple versions of Perl installed on your machine, you should make sure that the bindings are being installed for the version you are actually using for RNAFramework.

Best,
Danny

**Comment by coffeebond** [comment]
> Hello coffeebond,
> 
> this is a closed issue, you should have opened a new one. Anyway, it looks like you did not install the Perl bindings for Vienna. When you compile ViennaRNA from source, you should make sure that the Perl bindings are being installed as well. Also, in case you have multiple versions of Perl installed on your machine, you should make sure that the bindings are being installed for the version you are actually using for RNAFramework.
> 
> Best, Danny

Hi Danny,

Thank you for you reply. I felt this is more like a problem on my side than an issue of the program itself, so I didn't open a new issue.

I ran the RNAfold on a Ubuntu server so I can't really any changes to that. I will ask our IT to see if they can make the Perl binding happen for ViennaRNA.

Best,
Coffee

**Comment by dincarnato** [comment]
Hi coffeebond,

ViennaRNA has to be compiled from source.
Please check the installation instructions: https://www.tbi.univie.ac.at/RNA/ViennaRNA/doc/html/install.html

Best,
Danny

**Comment by coffeebond** [comment]
> Hi coffeebond,
> 
> ViennaRNA has to be compiled from source. Please check the installation instructions: https://www.tbi.univie.ac.at/RNA/ViennaRNA/doc/html/install.html
> 
> Best, Danny

Hi Danny,

IT told me they actually compiled from source with perl binding. Now I'm confused. 

Can you tell me how rc-fold uses ViennaRNA? It doesn't seem there is an input option to supply the path for RNA.pm.

Best,
Coffee

**Comment by dincarnato** [comment]
Hi Coffee,

rf-fold does not need the path to RNA.pm.
Paths to Perl modules, if non-conventional, are typically specified via the environment variable PERL5LIB.
I honestly think that, if the module is really installed, then the issue might be that you have 2 Perl versions on your machine.
Can you please try the following?

perl -MRNA -e 1

If you get an error like "Can't locate RNA.pm in @INC (you may need to install the RNA module)", it means that the either the Perl bindings are not installed, or that there might be another Perl version installed, with a different lib folder.

Danny

**Comment by coffeebond** [comment]
Hi Danny,

I tried the command as you suggested and I got this:

`Can't locate RNA.pm in @INC (you may need to install the RNA module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl/5.26.1/x86_64-linux-gnu-thread-multi /usr/local/lib/site_perl/5.26.1 /usr/local/lib/site_perl/x86_64-linux-gnu-thread-multi /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base).
BEGIN failed--compilation aborted.`

What do you think? I'm also asking our IT support and see if they know what to do next. 

Best,
Coffee

**Comment by dincarnato** [comment]
Hi Coffee,

it is clear at this point that either the IT team did not install the Perl bindings of ViennaRNA, or you have multiple Perl installs.
You mentioned before the RNA.pm module is on the system. What is the full path to the module?

Danny

**Comment by coffeebond** [comment]
So IT reinstall the ViennaRNA on one of the machines. I tried to run rf-fold again. This time different error popped out
`Can't locate XML/LibXML.pm in @INC (you may need to install the XML::LibXML module)`

**Comment by dincarnato** [comment]
Coffee,

the manual of RNA Framework clearly indicates the requirements.
The XML::LibXML module (which relies on the libxml2 library) is one of those.
You need to install it.

Best,
Danny

**Comment by coffeebond** [comment]
Yeah, I just saw that.

Perl module installation requires superuser privilege on our cluster. I have to contact IT again. Let me try it again.

**Comment by coffeebond** [comment]
OK. IT installed it and now it's running fine.

One more question about the output column "-log10(probability)". Is this pairing probability? I remember in RNAfold, the number in each ubox line of the '.ps' file is actually the square-root of pairing probability (https://algosb2019.sciencesconf.org/data/RNAtutorial.pdf). I assume you extracted from that number and I just want to make sure it means what I think it means.

Thanks!

**Comment by dincarnato** [comment]
Hi Coffee,

This is all detailed in the documentation at http://rnaframework-docs.readthedocs.io/.
The dp file contains the base-pairing probabilities expressed as -log10 of the probability. This is the standard file format that allows visualization of base-pairing probabilities in the IGV genome browser.

Danny

**Comment by coffeebond** [comment]
Hi Danny,

I've read your documentation, but I still want to confirm with you about the value of that column. I need to calculate the unpairing probability of each nucleotide so I need the summed pairing probability of each nucleotide to all possible pairing nucleotides. 

I was misled by the RNAfold output before (thinking the value is base-pairing probability, but it's in fact the square-root of the base-pairing probability) and got completely wrong conclusions. 

Best,
Coffee
